//! Deterministic C# model emitter (System.Text.Json, no external deps).

use crate::schema::Ir;

pub const HEADER: &str = "// <auto-generated>\n// Code generated by transport-rest-gen. DO NOT EDIT.\n// </auto-generated>\n\nusing System.Collections.Generic;\nusing System.Text.Json;\nusing System.Text.Json.Serialization;\n\n#nullable enable\n";

/// Map a wire enum value to a valid C# identifier.
fn sanitize_ident(value: &str) -> String {
    let mut out: String = value
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

fn pascal(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

pub fn cs_type(ty: &str, nullable: bool) -> String {
    fn base(ty: &str) -> String {
        if ty.starts_with("list<") || ty.starts_with("map<") {
            return base_of_collection(ty);
        }
        match ty {
            "string" => "string".into(),
            "int" => "long".into(),
            "float" => "double".into(),
            "bool" => "bool".into(),
            "datetime" => "DateTimeOffset".into(),
            other => other.to_string(),
        }
    }
    fn base_of_collection(ty: &str) -> String {
        if let Some(inner) = ty.strip_prefix("list<").and_then(|s| s.strip_suffix('>')) {
            let b = base(inner);
            return format!("IReadOnlyList<{b}>");
        }
        if let Some(inner) = ty.strip_prefix("map<").and_then(|s| s.strip_suffix('>')) {
            let b = base(inner);
            return format!("IReadOnlyDictionary<string, {b}>");
        }
        unreachable!()
    }
    let t = base(ty);
    if nullable && matches!(ty, "int" | "float" | "bool" | "datetime") {
        format!("{t}?")
    } else {
        t
    }
}

pub fn emit(ir: &Ir) -> String {
    let enum_names: std::collections::HashSet<&str> =
        ir.rest.enums.keys().map(String::as_str).collect();
    // Expand IR aliases to their concrete C# types at reference sites
    // (avoids file-level using-aliases, which broke under SDK 10).
    let alias_targets: Vec<(&str, String)> = ir
        .rest
        .aliases
        .iter()
        .map(|(name, def)| (name.as_str(), cs_type(&def.type_, false)))
        .collect();
    // Nullability policy: reference types are ALWAYS annotated nullable
    // (the wire may omit them); value types only when the field is optional.
    let cs_type_local = move |ty: &str, nullable: bool| -> String {
        let base = if enum_names.contains(ty) {
            "string".to_string()
        } else if let Some((_, expanded)) = alias_targets.iter().find(|(name, _)| *name == ty) {
            expanded.clone()
        } else {
            cs_type(ty, false)
        };
        let is_value_type = matches!(
            base.as_str(),
            "long" | "double" | "bool" | "System.DateTimeOffset"
        );
        if !is_value_type || nullable {
            format!("{base}?")
        } else {
            base
        }
    };
    let mut out = String::from(HEADER);

    out.push_str("\nnamespace TransportRest.Models;\n\n");

    for (name, def) in &ir.rest.enums {
        out.push_str(&format!(
            "/// <summary>{} Open enum: unknown wire values are valid strings.</summary>\npublic static class {}\n{{\n",
            def.doc.as_deref().unwrap_or(name.as_str()),
            name
        ));
        for v in &def.values {
            let member = sanitize_ident(v);
            out.push_str(&format!(
                "    /// <summary>Wire value <c>{v}</c>.</summary>\n    public const string {member} = \"{v}\";\n"
            ));
        }
        out.push_str("}\n\n");
    }

    // Tagged unions decode as raw JSON objects; dispatch on their "type" field.
    for name in ir.rest.unions.keys() {
        out.push_str(&format!(
            "/// <summary>{n} - tagged union (stop/station/location or unknown type); kept as raw JSON.</summary>\npublic sealed class {n}\n{{\n    public {n}(JsonElement raw) {{ Raw = raw; }}\n\n    public JsonElement Raw {{ get; }}\n}}\n\n",
            n = name
        ));
    }

    for (name, def) in ir.rest.models.iter().chain(ir.rest.envelopes.iter()) {
        out.push_str(&format!(
            "/// <summary>{}</summary>\npublic class {}\n{{\n",
            def.doc.as_deref().unwrap_or(name),
            name
        ));
        // extra-field tolerance note
        out.push_str(
            "    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>\n",
        );
        out.push_str("    [JsonExtensionData]\n    public Dictionary<string, JsonElement>? ExtensionData { get; set; }\n\n");
        for f in &def.fields {
            let json = f.json.as_deref().unwrap_or(&f.name);
            let mut prop = pascal(&f.name);
            if prop == "Type" {
                prop = "WireType".to_string(); // avoid clash with union discriminators
            }
            if prop == *name {
                // CS0542: member names cannot equal the enclosing type.
                prop = format!("{prop}Ref");
            }
            let doc = f
                .doc
                .as_ref()
                .map(|d| format!("    /// <summary>{d}</summary>\n"))
                .unwrap_or_default();
            out.push_str(&format!(
                "{doc}    [JsonPropertyName(\"{json}\")]\n    public {t} {prop} {{ get; set; }}\n\n",
                t = cs_type_local(&f.type_, f.opt)
            ));
        }
        out.push_str("}\n\n");
    }
    out
}
