//! Deterministic C# model emitter (System.Text.Json, no external deps).

use crate::schema::Ir;

pub const HEADER: &str = "// <auto-generated>\n// Code generated by transport-rest-gen. DO NOT EDIT.\n// </auto-generated>\n\nusing System.Collections.Generic;\nusing System.Text.Json;\nusing System.Text.Json.Serialization;\n";

/// Map a wire enum value to a valid C# identifier.
fn sanitize_ident(value: &str) -> String {
    let mut out: String = value
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

fn pascal(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

pub fn cs_type(ty: &str, nullable: bool) -> String {
    fn base(ty: &str) -> String {
        if ty.starts_with("list<") || ty.starts_with("map<") {
            return base_of_collection(ty);
        }
        match ty {
            "string" => "string".into(),
            "int" => "long".into(),
            "float" => "double".into(),
            "bool" => "bool".into(),
            "datetime" => "DateTimeOffset".into(),
            other => other.to_string(),
        }
    }
    fn base_of_collection(ty: &str) -> String {
        if let Some(inner) = ty.strip_prefix("list<").and_then(|s| s.strip_suffix('>')) {
            let b = base(inner);
            return format!("IReadOnlyList<{b}>");
        }
        if let Some(inner) = ty.strip_prefix("map<").and_then(|s| s.strip_suffix('>')) {
            let b = base(inner);
            return format!("IReadOnlyDictionary<string, {b}>");
        }
        unreachable!()
    }
    let t = base(ty);
    if nullable && matches!(ty, "int" | "float" | "bool" | "datetime") {
        format!("{t}?")
    } else {
        t
    }
}

pub fn emit(ir: &Ir) -> String {
    let mut out = String::from(HEADER);

    // using-aliases must precede every namespace element (CS1529).
    for (name, def) in &ir.rest.aliases {
        out.push_str(&format!(
            "using {} = {};\n",
            name,
            cs_type(&def.type_, false)
        ));
    }
    out.push_str("\nnamespace TransportRest.Models;\n\n");

    for (name, def) in &ir.rest.enums {
        out.push_str(&format!(
            "/// <summary>{}</summary>\npublic enum {} : string\n{{\n{}\n}}\n\n",
            def.doc.as_deref().unwrap_or(name),
            name,
            def.values
                .iter()
                .map(|v| {
                    let member = sanitize_ident(v);
                    format!("    [JsonStringEnumMemberName(\"{v}\")]\n    {member},")
                })
                .collect::<Vec<_>>()
                .join("\n")
        ));
    }

    // Tagged unions decode as raw JSON objects; dispatch on their "type" field.
    for name in ir.rest.unions.keys() {
        out.push_str(&format!(
            "/// <summary>{n} - tagged union (stop/station/location or unknown type); kept as raw JSON.</summary>\npublic sealed class {n}\n{{\n    public {n}(JsonElement raw) {{ Raw = raw; }}\n\n    public JsonElement Raw {{ get; }}\n}}\n\n",
            n = name
        ));
    }

    for (name, def) in ir.rest.models.iter().chain(ir.rest.envelopes.iter()) {
        out.push_str(&format!(
            "/// <summary>{}</summary>\npublic class {}\n{{\n",
            def.doc.as_deref().unwrap_or(name),
            name
        ));
        // extra-field tolerance note
        out.push_str(
            "    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>\n",
        );
        out.push_str("    [JsonExtensionData]\n    public Dictionary<string, JsonElement>? ExtensionData { get; set; }\n\n");
        for f in &def.fields {
            let json = f.json.as_deref().unwrap_or(&f.name);
            let mut prop = pascal(&f.name);
            if prop == "Type" {
                prop = "WireType".to_string(); // avoid clash with union discriminators
            }
            let doc = f
                .doc
                .as_ref()
                .map(|d| format!("    /// <summary>{d}</summary>\n"))
                .unwrap_or_default();
            out.push_str(&format!(
                "{doc}    [JsonPropertyName(\"{json}\")]\n    public {t} {prop} {{ get; set; }}\n\n",
                t = cs_type(&f.type_, f.opt)
            ));
        }
        out.push_str("}\n\n");
    }
    out
}
