//! Deterministic Go model emitter.

use crate::schema::Ir;

pub const HEADER: &str = "// Code generated by transport-rest-gen. DO NOT EDIT.\n\npackage transportrest\n\nimport \"time\"\n\n";

fn snake_to_camel(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

pub fn go_type(ty: &str) -> String {
    if let Some(inner) = ty.strip_prefix("list<").and_then(|s| s.strip_suffix('>')) {
        return format!("[]{}", go_type(inner));
    }
    if let Some(_inner) = ty.strip_prefix("map<").and_then(|s| s.strip_suffix('>')) {
        // value type only matters at the call sites; keep generic json.RawMessage-free maps
        return "map[string]any".to_string();
    }
    match ty {
        "string" => "string".into(),
        // Upstream mixes integers and floats for the same fields (delays!),
        // so decode all numbers as float64.
        "int" => "float64".into(),
        "float" => "float64".into(),
        "bool" => "bool".into(),
        "datetime" => "*time.Time".into(),
        // Model/union references; nullability via pointer at the field site.
        other => other.to_string(),
    }
}

pub fn emit(ir: &Ir) -> String {
    let mut out = String::from(HEADER);

    out.push_str("// Enums and aliases are represented as their underlying scalar types;\n// see schema/types.json for the known values. Tagged unions decode as raw JSON\n// objects; dispatch on their \"type\" field.\ntype (\n\tMode = string\n\tPrognosisType = string\n\tRemarkKind = string\n\tDbProfile = string\n\tProducts = map[string]bool\n\tIds = map[string]string\n\tServiceDays = map[string]bool\n\tOpeningHours = map[string]string\n");
    for name in ir.rest.unions.keys() {
        out.push_str(&format!("\t{name} = map[string]any\n"));
    }
    out.push_str(")\n\n");

    for (name, def) in ir.rest.models.iter().chain(ir.rest.envelopes.iter()) {
        if let Some(doc) = &def.doc {
            out.push_str(&format!("// {name} – {doc}\n"));
        }
        out.push_str(&format!("type {name} struct {{\n"));
        for f in &def.fields {
            if let Some(doc) = &f.doc {
                out.push_str(&format!("\t// {doc}\n"));
            }
            let json = f.json.as_deref().unwrap_or(&f.name);
            let gt = go_type(&f.type_);
            // Pointers express nullability; collections and datetimes
            // (already `*time.Time`) never get an extra one.
            let needs_ptr = match f.type_.as_str() {
                "list<" | "map<" => false,
                _ => !f.type_.starts_with("list<") && !f.type_.starts_with("map<"),
            } && !matches!(f.type_.as_str(), "datetime");
            let is_collection = f.type_.starts_with("list<") || f.type_.starts_with("map<");
            let ptr = if (!is_collection && needs_ptr)
                || (!is_collection
                    && matches!(f.type_.as_str(), "string" | "bool" | "int" | "float")
                    && f.opt)
            {
                "*"
            } else {
                ""
            };
            let omitempty = if f.opt { ",omitempty" } else { "" };
            let field_type = format!("{ptr}{gt}");
            let tag = format!("json:\"{json}{omitempty}\"");
            out.push_str(&format!(
                "\t{} {} `{}`\n",
                snake_to_camel(&f.name),
                field_type,
                tag
            ));
        }
        out.push_str("}\n\n");
    }
    out
}
