//! Deterministic Java model emitter (records + Jackson annotations).

use crate::schema::Ir;

pub const HEADER: &str = "// Code generated by transport-rest-gen. DO NOT EDIT.\n\npackage io.transportrest.models;\n\nimport com.fasterxml.jackson.annotation.JsonAnyGetter;\nimport com.fasterxml.jackson.annotation.JsonAnySetter;\nimport com.fasterxml.jackson.annotation.JsonIgnoreProperties;\nimport com.fasterxml.jackson.annotation.JsonProperty;\n\nimport java.time.OffsetDateTime;\nimport java.util.HashMap;\nimport java.util.List;\nimport java.util.Map;\n\n";

fn pascal(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

pub fn java_type(ty: &str, _opt: bool) -> String {
    if let Some(inner) = ty.strip_prefix("list<").and_then(|s| s.strip_suffix('>')) {
        return format!("List<{}>", java_type(inner, false));
    }
    if let Some(inner) = ty.strip_prefix("map<").and_then(|s| s.strip_suffix('>')) {
        return format!("Map<String, {}>", java_type(inner, false));
    }
    match ty {
        "string" => "String".to_string(),
        // boxed types so nullability is expressible
        "int" => "Long".to_string(),
        "float" => "Double".to_string(),
        "bool" => "Boolean".to_string(),
        "datetime" => "OffsetDateTime".to_string(),
        other => other.to_string(),
    }
}

pub fn emit(ir: &Ir) -> String {
    let mut out = String::from(HEADER);

    for (name, def) in &ir.rest.enums {
        out.push_str(&format!(
            "/** {} */\npublic enum {}\n{{\n{}\n}}\n\n",
            def.doc.as_deref().unwrap_or(name),
            name,
            def.values
                .iter()
                .map(|v| format!("    @JsonProperty(\"{v}\")\n    {v},"))
                .collect::<Vec<_>>()
                .join("\n")
        ));
    }

    for (name, def) in ir.rest.models.iter().chain(ir.rest.envelopes.iter()) {
        let doc = def.doc.as_deref().unwrap_or(name);
        out.push_str(&format!(
            "/** {doc} */\n@JsonIgnoreProperties(ignoreUnknown = true)\n"
        ));
        out.push_str(&format!("public final class {name}\n{{\n"));
        out.push_str("    private final Map<String, Object> unknownFields = new HashMap<>();\n\n");
        out.push_str("    @JsonAnyGetter\n    public Map<String, Object> getUnknownFields() { return unknownFields; }\n\n    @JsonAnySetter\n    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }\n\n");
        // fields
        for f in &def.fields {
            let json = f.json.as_deref().unwrap_or(&f.name);
            out.push_str(&format!(
                "    @JsonProperty(\"{json}\")\n    private final {t} {name_};\n\n",
                t = java_type(&f.type_, f.opt),
                name_ = f.name,
            ));
        }
        // constructor
        out.push_str(&format!("    public {name}(\n"));
        let params: Vec<String> = def
            .fields
            .iter()
            .map(|f| {
                format!(
                    "            @JsonProperty(\"{}\") {} {}",
                    f.json.as_deref().unwrap_or(&f.name),
                    java_type(&f.type_, f.opt),
                    f.name
                )
            })
            .collect();
        out.push_str(&params.join(",\n"));
        out.push_str("\n    )\n    {\n");
        for f in &def.fields {
            out.push_str(&format!("        this.{} = {};\n", f.name, f.name));
        }
        out.push_str("    }\n\n");
        // getters
        for f in &def.fields {
            out.push_str(&format!(
                "    public {} get{}() {{ return {}; }}\n\n",
                java_type(&f.type_, f.opt),
                pascal(&f.name),
                f.name
            ));
        }
        out.push_str("}\n\n");
    }
    out
}
