//! Deterministic Python model emitter (stdlib-only dataclasses).

use crate::schema::Ir;

pub const HEADER: &str = "\"\"\"Generated by transport-rest-gen. DO NOT EDIT.\n\nSource of truth: schema/*.json (see docs/API_ANALYSIS.md).\nAll models ignore unknown JSON fields and tolerate null values.\n\"\"\"\n\nfrom __future__ import annotations\n\nimport dataclasses\nimport datetime as _dt\nfrom typing import Any, Optional\n\n";

fn snake(s: &str) -> String {
    s.to_owned()
}

/// Map an IR type to a Python annotation string.
pub fn map_type(ty: &str) -> String {
    if let Some(inner) = ty.strip_prefix("list<").and_then(|s| s.strip_suffix('>')) {
        return format!("list[{}]", map_type(inner));
    }
    if let Some(inner) = ty.strip_prefix("map<").and_then(|s| s.strip_suffix('>')) {
        return format!("dict[str, {}]", map_type(inner));
    }
    match ty {
        "string" => "str".into(),
        "int" => "int".into(),
        "float" | "int_or_float" => "float".into(),
        "bool" => "bool".into(),
        "datetime" => "_dt.datetime".into(),
        other => format!("Optional[{other}]"),
    }
}

/// Emit a tolerant `from_dict` body for one model.
fn from_dict_body(_class: &str, fields: &[crate::schema::FieldDef]) -> String {
    let mut out = String::new();
    out.push_str("        obj = dict(obj)\n");
    out.push_str("        unknown = {k: v for k, v in obj.items()}\n");
    out.push_str("        _ = unknown  # unknown fields are intentionally ignored\n");
    for f in fields {
        let json = f.json.as_deref().unwrap_or(&f.name);
        let py_name = snake(&f.name);
        let raw = format!("obj.get(\"{json}\")");
        let expr = match f.type_.as_str() {
            "datetime" => {
                if f.opt {
                    format!("(_parse_dt({raw}) if {raw} is not None else None)")
                } else {
                    format!("_parse_dt({raw})")
                }
            }
            t if is_model_ref(t) => {
                if f.opt {
                    format!("({t}.from_dict({raw}) if isinstance({raw}, dict) else {raw})")
                } else {
                    format!("({t}.from_dict({raw}) if isinstance({raw}, dict) else {raw})")
                }
            }
            t if t.starts_with("list<") && is_model_ref(t.trim_start_matches("list<").trim_end_matches('>')) => format!(
                "[{t2}.from_dict(i) if isinstance(i, dict) else i for i in ({raw} or [])]",
                t2 = t.trim_start_matches("list<").trim_end_matches('>')
            ),
            _ => raw,
        };
        out.push_str(&format!("        {py_name} = {expr}\n"));
    }
    out.push_str(&format!(
        "        return cls(\n{}\n        )\n",
        fields
            .iter()
            .map(|f| format!("            {}={},", snake(&f.name), snake(&f.name)))
            .collect::<Vec<_>>()
            .join("\n")
    ));
    out
}

fn is_model_ref(ty: &str) -> bool {
    matches!(
        ty,
        "Location" | "Stop" | "Station" | "Line" | "Operator" | "Remark" | "Price"
            | "Cycle" | "Stopover" | "Leg" | "Journey" | "Trip" | "Departure"
            | "Frame" | "Movement" | "ReachableDuration" | "Polyline"
            | "PolylineFeature" | "GeometryPoint"
    )
}

fn union_from_dict(union: &crate::schema::UnionDef) -> String {
    let mut out = String::from("    if not isinstance(obj, dict):\n        return obj\n");
    out.push_str("    tag = obj.get(\"type\")\n");
    for v in &union.variants {
        out.push_str(&format!(
            "    if tag == \"{}\":\n        try:\n            return {}.from_dict(obj)\n        except Exception:\n            pass\n",
            v.value, v.type_
        ));
    }
    // open unions fall back to the raw object
    out.push_str("    return obj\n");
    out
}

pub fn emit(ir: &Ir) -> String {
    let mut out = String::from(HEADER);

    out.push_str("# ---------------------------------------------------------------------------\n# Shared aliases (see schema/types.json for known keys/values)\n# ---------------------------------------------------------------------------\n\nProducts = dict[str, bool]\nIds = dict[str, str]\nServiceDays = dict[str, bool]\nOpeningHours = dict[str, str]\n\n\ndef _parse_dt(value: Any) -> Any:\n    try:\n        return _dt.datetime.fromisoformat(value.replace(\"Z\", \"+00:00\"))\n    except (TypeError, ValueError, AttributeError):\n        return value\n\n");

    out.push_str("# ---------------------------------------------------------------------------\n# Tagged unions (dispatch on the wire `type` field; unknown -> raw dict)\n# ---------------------------------------------------------------------------\n\n");

    // forward references: emit all classes first, then attach from_dict methods
    for (name, def) in &ir.rest.enums {
        let doc = def.doc.as_deref().unwrap_or(name);
        out.push_str(&format!("{name} = str  # open enum: {}\n", doc.replace('\n', " ")));
    }

    for (name, def) in ir.rest.models.iter() {
        out.push_str(&docstring(def.doc.as_deref(), 0));
        out.push_str(&format!("@dataclasses.dataclass\nclass {name}:\n"));
        if def.fields.is_empty() {
            out.push_str("    pass\n");
        }
        for f in &def.fields {
            let ann = map_type(&f.type_);
            out.push_str(&format!("    {}: {}", snake(&f.name), ann));
            if f.opt || !is_required(&f.type_) {
                out.push_str(" = None");
            }
            out.push('\n');
        }
        out.push_str("\n    @classmethod\n    def from_dict(cls, obj: Any) -> ");
        out.push_str(name);
        out.push_str(":\n");
        out.push_str(&from_dict_body(name, &def.fields));
        out.push('\n');
    }

    for (name, def) in ir.rest.unions.iter() {
        out.push_str(&docstring(def.doc.as_deref(), 0));
        out.push_str(&format!("{name} = object  # see from_dict dispatch below\n\n"));
        let _ = def;
    }

    // Envelope models
    for (name, def) in ir.rest.envelopes.iter() {
        out.push_str(&docstring(def.doc.as_deref(), 0));
        out.push_str(&format!("@dataclasses.dataclass\nclass {name}:\n"));
        for f in &def.fields {
            let ann = map_type(&f.type_);
            out.push_str(&format!("    {}: {}", snake(&f.name), ann));
            if f.opt || !is_required(&f.type_) {
                out.push_str(" = None");
            }
            out.push('\n');
        }
        out.push_str(&format!(
            "\n    @classmethod\n    def from_dict(cls, obj: Any) -> \"{name}\":\n"
        ));
        out.push_str(&from_dict_body(name, &def.fields));
        out.push('\n');
    }

    // union dispatch helpers appended after class definitions
    for (name, def) in ir.rest.unions.iter() {
        out.push_str(&format!(
            "def parse_{name}(obj: Any) -> Any:\n    \"\"\"Dispatch on the wire `type` tag; returns raw dicts for unknown types.\"\"\"\n"
        ));
        out.push_str(&union_from_dict(def));
        out.push('\n');
    }

    out
}

fn is_required(_ty: &str) -> bool {
    // only plain scalars are required-positionally; everything nullable defaults
    false
}

fn docstring(doc: Option<&str>, indent: usize) -> String {
    match doc {
        Some(d) => {
            let pad = " ".repeat(indent);
            format!("{pad}\"\"\"{}\"\"\"\n", d.replace('\n', " "))
        }
        None => String::new(),
    }
}
