//! Deterministic TypeScript model emitter.

use crate::schema::Ir;

pub const HEADER: &str = "/* eslint-disable */\n/**\n * Generated by transport-rest-gen. DO NOT EDIT.\n *\n * Source of truth: schema/*.json (see docs/API_ANALYSIS.md).\n */\n\n";

/// Map an IR type expression to a TypeScript type.
pub fn map_type(ty: &str) -> String {
    if let Some(inner) = ty.strip_prefix("list<").and_then(|s| s.strip_suffix('>')) {
        return format!("{}[]", wrap_inline(map_type(inner)));
    }
    if let Some(inner) = ty.strip_prefix("map<").and_then(|s| s.strip_suffix('>')) {
        return format!("Record<string, {}>", map_type(inner));
    }
    match ty {
        "string" => "string".into(),
        "int" | "float" => "number".into(),
        "bool" => "boolean".into(),
        // ISO-8601 string with offset
        "datetime" => "string".into(),
        other => other.to_string(),
    }
}

fn wrap_inline(ty: String) -> String {
    if ty.ends_with("[]") || ty.contains(' ') {
        format!("({ty})")
    } else {
        ty
    }
}

fn doc_comment(doc: Option<&String>, indent: &str) -> String {
    match doc {
        Some(d) => {
            let mut out = format!("{indent}/**\n");
            for line in d.lines() {
                out.push_str(&format!("{indent} * {line}\n"));
            }
            out.push_str(&format!("{indent} */\n"));
            out
        }
        None => String::new(),
    }
}

pub fn emit(ir: &Ir) -> String {
    let mut out = String::from(HEADER);
    out.push_str("// ---------------------------------------------------------------------------\n// Shared aliases\n// ---------------------------------------------------------------------------\n\n");
    for (name, alias) in &ir.rest.aliases {
        let doc = doc_comment(alias.doc.as_ref(), "");
        out.push_str(&format!(
            "{doc}export type {name} = {};\n\n",
            map_type(&alias.type_)
        ));
    }

    out.push_str("// ---------------------------------------------------------------------------\n// Open enums (unknown values stay valid)\n// ---------------------------------------------------------------------------\n\n");
    for (name, def) in &ir.rest.enums {
        out.push_str(&doc_comment(def.doc.as_ref(), ""));
        let values = def
            .values
            .iter()
            .map(|v| format!("  | '{v}'"))
            .collect::<Vec<_>>()
            .join("\n");
        out.push_str(&format!(
            "export type {name} =\n{values}\n  | (string & {{}});\n\n"
        ));
    }

    out.push_str("// ---------------------------------------------------------------------------\n// Tagged unions (discriminated by `type`, unknown types captured verbatim)\n// ---------------------------------------------------------------------------\n\n");
    for (name, def) in &ir.rest.unions {
        out.push_str(&doc_comment(def.doc.as_ref(), ""));
        let variants = def
            .variants
            .iter()
            .map(|v| format!("  | ({{ type: '{}'; }} & {})", v.value, v.type_))
            .collect::<Vec<_>>()
            .join("\n");
        out.push_str(&format!(
            "export type {name} =\n{variants}\n  | {{ type: (string & {{}}) }};\n\n"
        ));
    }

    out.push_str("// ---------------------------------------------------------------------------\n// Models\n// ---------------------------------------------------------------------------\n\n");
    for (name, def) in ir.rest.models.iter() {
        out.push_str(&doc_comment(def.doc.as_ref(), ""));
        out.push_str(&format!("export interface {name} {{\n"));
        for field in &def.fields {
            out.push_str(&doc_comment(field.doc.as_ref(), "  "));
            let json = field.json.as_deref().unwrap_or(&field.name);
            let optional = if field.opt { "?" } else { "" };
            out.push_str(&format!(
                "  '{json}'{optional}: {} | null;\n",
                map_type(&field.type_)
            ));
        }
        out.push_str("  [key: string]: unknown; // tolerate future fields\n}\n\n");
    }

    for (name, def) in ir.rest.envelopes.iter() {
        out.push_str(&doc_comment(def.doc.as_ref(), ""));
        out.push_str(&format!("export interface {name} {{\n"));
        for field in &def.fields {
            out.push_str(&doc_comment(field.doc.as_ref(), "  "));
            let json = field.json.as_deref().unwrap_or(&field.name);
            let optional = if field.opt { "?" } else { "" };
            out.push_str(&format!(
                "  '{json}'{optional}: {} | null;\n",
                map_type(&field.type_)
            ));
        }
        out.push_str("  [key: string]: unknown;\n}\n\n");
    }

    out
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn deterministic_output() {
        let dir = std::path::Path::new("../../schema");
        let ir = crate::schema::load_ir(dir).expect("valid repo schema");
        let a = emit(&ir);
        let b = emit(&ir);
        assert_eq!(a, b);
        assert!(a.starts_with(crate::ts::HEADER));
        assert!(a.contains("export interface Stop"));
        assert!(a.contains("export type LocationResult"));
    }

    #[test]
    fn type_mapping() {
        assert_eq!(map_type("list<Line>"), "Line[]");
        assert_eq!(map_type("map<bool>"), "Record<string, boolean>");
        assert_eq!(map_type("datetime"), "string");
    }
}
