// Code generated by transport-rest-gen. DO NOT EDIT.

package io.transportrest.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Accessibility */
public enum Accessibility
{
    @JsonProperty("partial")
    PARTIAL,
    @JsonProperty("complete")
    COMPLETE,
}

/** AgeGroup */
public enum AgeGroup
{
    @JsonProperty("B")
    B,
    @JsonProperty("E")
    E,
    @JsonProperty("K")
    K,
    @JsonProperty("S")
    S,
    @JsonProperty("Y")
    Y,
}

/** db-vendo backend profile selector of the DB instance. */
public enum DbProfile
{
    @JsonProperty("dbnav")
    DBNAV,
    @JsonProperty("db")
    DB,
    @JsonProperty("dbweb")
    DBWEB,
}

/** LoyaltyCard */
public enum LoyaltyCard
{
    @JsonProperty("bahncard-1st-25")
    BAHNCARD_1ST_25,
    @JsonProperty("bahncard-2nd-25")
    BAHNCARD_2ND_25,
    @JsonProperty("bahncard-1st-50")
    BAHNCARD_1ST_50,
    @JsonProperty("bahncard-2nd-50")
    BAHNCARD_2ND_50,
    @JsonProperty("bahncard-1st-100")
    BAHNCARD_1ST_100,
    @JsonProperty("bahncard-2nd-100")
    BAHNCARD_2ND_100,
    @JsonProperty("vorteilscard")
    VORTEILSCARD,
    @JsonProperty("halbtaxabo")
    HALBTAXABO,
    @JsonProperty("generalabonnement-1st")
    GENERALABONNEMENT_1ST,
    @JsonProperty("generalabonnement-2nd")
    GENERALABONNEMENT_2ND,
    @JsonProperty("nl-40")
    NL_40,
    @JsonProperty("at-klimaticket")
    AT_KLIMATICKET,
}

/** Means of transport mode (FPTF). Open enum: unknown wire values map to the fallback variant. */
public enum Mode
{
    @JsonProperty("aircraft")
    AIRCRAFT,
    @JsonProperty("bicycle")
    BICYCLE,
    @JsonProperty("bus")
    BUS,
    @JsonProperty("car")
    CAR,
    @JsonProperty("gondola")
    GONDOLA,
    @JsonProperty("taxi")
    TAXI,
    @JsonProperty("train")
    TRAIN,
    @JsonProperty("walking")
    WALKING,
    @JsonProperty("watercraft")
    WATERCRAFT,
}

/** Reliability class of a prognosis. */
public enum PrognosisType
{
    @JsonProperty("calculated")
    CALCULATED,
    @JsonProperty("prognosed")
    PROGNOSED,
}

/** Discriminator of remark objects; FPTF hint/status/warning are merged into one model. */
public enum RemarkKind
{
    @JsonProperty("hint")
    HINT,
    @JsonProperty("status")
    STATUS,
    @JsonProperty("warning")
    WARNING,
    @JsonProperty("foreign-id")
    FOREIGN_ID,
    @JsonProperty("local-fare-zone")
    LOCAL_FARE_ZONE,
    @JsonProperty("stop-dhid")
    STOP_DHID,
    @JsonProperty("stop-website")
    STOP_WEBSITE,
    @JsonProperty("transit-authority")
    TRANSIT_AUTHORITY,
}

/** REALTIME is the default and excludes cancelled journeys; HYBRID includes them and fully supports pagination. */
public enum RoutingMode
{
    @JsonProperty("FULL")
    FULL,
    @JsonProperty("HYBRID")
    HYBRID,
    @JsonProperty("INFOS")
    INFOS,
    @JsonProperty("OFF")
    OFF,
    @JsonProperty("REALTIME")
    REALTIME,
    @JsonProperty("SERVER_DEFAULT")
    SERVER_DEFAULT,
}

/** WalkingSpeed */
public enum WalkingSpeed
{
    @JsonProperty("slow")
    SLOW,
    @JsonProperty("normal")
    NORMAL,
    @JsonProperty("fast")
    FAST,
}

/** Cycle times of a line/trip in minutes. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Cycle
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("min")
    private final Long min;

    @JsonProperty("max")
    private final Long max;

    @JsonProperty("nr")
    private final Long nr;

    public Cycle(
            @JsonProperty("min") Long min,
            @JsonProperty("max") Long max,
            @JsonProperty("nr") Long nr
    )
    {
        this.min = min;
        this.max = max;
        this.nr = nr;
    }

    public Long getMin() { return min; }

    public Long getMax() { return max; }

    public Long getNr() { return nr; }

}

/** A departure or arrival board entry (OpenAPI schema name: Alternative). */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Departure
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("tripId")
    private final String trip_id;

    @JsonProperty("stop")
    private final StopOrStation stop;

    @JsonProperty("location")
    private final Location location;

    @JsonProperty("line")
    private final Line line;

    @JsonProperty("direction")
    private final String direction;

    @JsonProperty("provenance")
    private final String provenance;

    @JsonProperty("origin")
    private final Place origin;

    @JsonProperty("destination")
    private final Place destination;

    @JsonProperty("when")
    private final OffsetDateTime when;

    @JsonProperty("plannedWhen")
    private final OffsetDateTime planned_when;

    @JsonProperty("prognosedWhen")
    private final OffsetDateTime prognosed_when;

    @JsonProperty("delay")
    private final Long delay;

    @JsonProperty("platform")
    private final String platform;

    @JsonProperty("plannedPlatform")
    private final String planned_platform;

    @JsonProperty("prognosedPlatform")
    private final String prognosed_platform;

    @JsonProperty("prognosisType")
    private final PrognosisType prognosis_type;

    @JsonProperty("remarks")
    private final List<Remark> remarks;

    @JsonProperty("cancelled")
    private final Boolean cancelled;

    @JsonProperty("loadFactor")
    private final String load_factor;

    @JsonProperty("previousStopovers")
    private final List<Stopover> previous_stopovers;

    @JsonProperty("nextStopovers")
    private final List<Stopover> next_stopovers;

    @JsonProperty("frames")
    private final List<Frame> frames;

    @JsonProperty("polyline")
    private final Polyline polyline;

    @JsonProperty("currentTripPosition")
    private final Location current_trip_position;

    public Departure(
            @JsonProperty("tripId") String trip_id,
            @JsonProperty("stop") StopOrStation stop,
            @JsonProperty("location") Location location,
            @JsonProperty("line") Line line,
            @JsonProperty("direction") String direction,
            @JsonProperty("provenance") String provenance,
            @JsonProperty("origin") Place origin,
            @JsonProperty("destination") Place destination,
            @JsonProperty("when") OffsetDateTime when,
            @JsonProperty("plannedWhen") OffsetDateTime planned_when,
            @JsonProperty("prognosedWhen") OffsetDateTime prognosed_when,
            @JsonProperty("delay") Long delay,
            @JsonProperty("platform") String platform,
            @JsonProperty("plannedPlatform") String planned_platform,
            @JsonProperty("prognosedPlatform") String prognosed_platform,
            @JsonProperty("prognosisType") PrognosisType prognosis_type,
            @JsonProperty("remarks") List<Remark> remarks,
            @JsonProperty("cancelled") Boolean cancelled,
            @JsonProperty("loadFactor") String load_factor,
            @JsonProperty("previousStopovers") List<Stopover> previous_stopovers,
            @JsonProperty("nextStopovers") List<Stopover> next_stopovers,
            @JsonProperty("frames") List<Frame> frames,
            @JsonProperty("polyline") Polyline polyline,
            @JsonProperty("currentTripPosition") Location current_trip_position
    )
    {
        this.trip_id = trip_id;
        this.stop = stop;
        this.location = location;
        this.line = line;
        this.direction = direction;
        this.provenance = provenance;
        this.origin = origin;
        this.destination = destination;
        this.when = when;
        this.planned_when = planned_when;
        this.prognosed_when = prognosed_when;
        this.delay = delay;
        this.platform = platform;
        this.planned_platform = planned_platform;
        this.prognosed_platform = prognosed_platform;
        this.prognosis_type = prognosis_type;
        this.remarks = remarks;
        this.cancelled = cancelled;
        this.load_factor = load_factor;
        this.previous_stopovers = previous_stopovers;
        this.next_stopovers = next_stopovers;
        this.frames = frames;
        this.polyline = polyline;
        this.current_trip_position = current_trip_position;
    }

    public String getTripId() { return trip_id; }

    public StopOrStation getStop() { return stop; }

    public Location getLocation() { return location; }

    public Line getLine() { return line; }

    public String getDirection() { return direction; }

    public String getProvenance() { return provenance; }

    public Place getOrigin() { return origin; }

    public Place getDestination() { return destination; }

    public OffsetDateTime getWhen() { return when; }

    public OffsetDateTime getPlannedWhen() { return planned_when; }

    public OffsetDateTime getPrognosedWhen() { return prognosed_when; }

    public Long getDelay() { return delay; }

    public String getPlatform() { return platform; }

    public String getPlannedPlatform() { return planned_platform; }

    public String getPrognosedPlatform() { return prognosed_platform; }

    public PrognosisType getPrognosisType() { return prognosis_type; }

    public List<Remark> getRemarks() { return remarks; }

    public Boolean getCancelled() { return cancelled; }

    public String getLoadFactor() { return load_factor; }

    public List<Stopover> getPreviousStopovers() { return previous_stopovers; }

    public List<Stopover> getNextStopovers() { return next_stopovers; }

    public List<Frame> getFrames() { return frames; }

    public Polyline getPolyline() { return polyline; }

    public Location getCurrentTripPosition() { return current_trip_position; }

}

/** Radar frame: position of a vehicle between two places at offset t. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Frame
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("origin")
    private final Place origin;

    @JsonProperty("destination")
    private final Place destination;

    @JsonProperty("t")
    private final Double t;

    public Frame(
            @JsonProperty("origin") Place origin,
            @JsonProperty("destination") Place destination,
            @JsonProperty("t") Double t
    )
    {
        this.origin = origin;
        this.destination = destination;
        this.t = t;
    }

    public Place getOrigin() { return origin; }

    public Place getDestination() { return destination; }

    public Double getT() { return t; }

}

/** GeoJSON Point geometry. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class GeometryPoint
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("coordinates")
    private final List<Double> coordinates;

    public GeometryPoint(
            @JsonProperty("coordinates") List<Double> coordinates
    )
    {
        this.coordinates = coordinates;
    }

    public List<Double> getCoordinates() { return coordinates; }

}

/** A computed set of directions to get from A to B at a specific time. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Journey
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("id")
    private final String id;

    @JsonProperty("refreshToken")
    private final String refresh_token;

    @JsonProperty("legs")
    private final List<Leg> legs;

    @JsonProperty("remarks")
    private final List<Remark> remarks;

    @JsonProperty("price")
    private final Price price;

    @JsonProperty("cycle")
    private final Cycle cycle;

    @JsonProperty("serviceDays")
    private final ServiceDays service_days;

    @JsonProperty("scheduledDays")
    private final ServiceDays scheduled_days;

    public Journey(
            @JsonProperty("id") String id,
            @JsonProperty("refreshToken") String refresh_token,
            @JsonProperty("legs") List<Leg> legs,
            @JsonProperty("remarks") List<Remark> remarks,
            @JsonProperty("price") Price price,
            @JsonProperty("cycle") Cycle cycle,
            @JsonProperty("serviceDays") ServiceDays service_days,
            @JsonProperty("scheduledDays") ServiceDays scheduled_days
    )
    {
        this.id = id;
        this.refresh_token = refresh_token;
        this.legs = legs;
        this.remarks = remarks;
        this.price = price;
        this.cycle = cycle;
        this.service_days = service_days;
        this.scheduled_days = scheduled_days;
    }

    public String getId() { return id; }

    public String getRefreshToken() { return refresh_token; }

    public List<Leg> getLegs() { return legs; }

    public List<Remark> getRemarks() { return remarks; }

    public Price getPrice() { return price; }

    public Cycle getCycle() { return cycle; }

    public ServiceDays getServiceDays() { return service_days; }

    public ServiceDays getScheduledDays() { return scheduled_days; }

}

/** One leg of a journey. Walking/transfer legs have walking=true and no line. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Leg
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("tripId")
    private final String trip_id;

    @JsonProperty("origin")
    private final Place origin;

    @JsonProperty("destination")
    private final Place destination;

    @JsonProperty("line")
    private final Line line;

    @JsonProperty("direction")
    private final String direction;

    @JsonProperty("operator")
    private final Operator operator;

    @JsonProperty("departure")
    private final OffsetDateTime departure;

    @JsonProperty("plannedDeparture")
    private final OffsetDateTime planned_departure;

    @JsonProperty("prognosedDeparture")
    private final OffsetDateTime prognosed_departure;

    @JsonProperty("departureDelay")
    private final Long departure_delay;

    @JsonProperty("departurePlatform")
    private final String departure_platform;

    @JsonProperty("plannedDeparturePlatform")
    private final String planned_departure_platform;

    @JsonProperty("prognosedDeparturePlatform")
    private final String prognosed_departure_platform;

    @JsonProperty("departurePrognosisType")
    private final PrognosisType departure_prognosis_type;

    @JsonProperty("arrival")
    private final OffsetDateTime arrival;

    @JsonProperty("plannedArrival")
    private final OffsetDateTime planned_arrival;

    @JsonProperty("prognosedArrival")
    private final OffsetDateTime prognosed_arrival;

    @JsonProperty("arrivalDelay")
    private final Long arrival_delay;

    @JsonProperty("arrivalPlatform")
    private final String arrival_platform;

    @JsonProperty("plannedArrivalPlatform")
    private final String planned_arrival_platform;

    @JsonProperty("prognosedArrivalPlatform")
    private final String prognosed_arrival_platform;

    @JsonProperty("arrivalPrognosisType")
    private final PrognosisType arrival_prognosis_type;

    @JsonProperty("stopovers")
    private final List<Stopover> stopovers;

    @JsonProperty("remarks")
    private final List<Remark> remarks;

    @JsonProperty("walking")
    private final Boolean walking;

    @JsonProperty("transfer")
    private final Boolean transfer;

    @JsonProperty("distance")
    private final Double distance;

    @JsonProperty("public")
    private final Boolean public;

    @JsonProperty("reachable")
    private final Boolean reachable;

    @JsonProperty("cancelled")
    private final Boolean cancelled;

    @JsonProperty("loadFactor")
    private final String load_factor;

    @JsonProperty("cycle")
    private final Cycle cycle;

    @JsonProperty("alternatives")
    private final List<Departure> alternatives;

    @JsonProperty("polyline")
    private final Polyline polyline;

    @JsonProperty("price")
    private final Price price;

    @JsonProperty("schedule")
    private final Long schedule;

    @JsonProperty("currentLocation")
    private final Location current_location;

    @JsonProperty("checkin")
    private final Boolean checkin;

    @JsonProperty("serviceDays")
    private final ServiceDays service_days;

    @JsonProperty("scheduledDays")
    private final ServiceDays scheduled_days;

    public Leg(
            @JsonProperty("tripId") String trip_id,
            @JsonProperty("origin") Place origin,
            @JsonProperty("destination") Place destination,
            @JsonProperty("line") Line line,
            @JsonProperty("direction") String direction,
            @JsonProperty("operator") Operator operator,
            @JsonProperty("departure") OffsetDateTime departure,
            @JsonProperty("plannedDeparture") OffsetDateTime planned_departure,
            @JsonProperty("prognosedDeparture") OffsetDateTime prognosed_departure,
            @JsonProperty("departureDelay") Long departure_delay,
            @JsonProperty("departurePlatform") String departure_platform,
            @JsonProperty("plannedDeparturePlatform") String planned_departure_platform,
            @JsonProperty("prognosedDeparturePlatform") String prognosed_departure_platform,
            @JsonProperty("departurePrognosisType") PrognosisType departure_prognosis_type,
            @JsonProperty("arrival") OffsetDateTime arrival,
            @JsonProperty("plannedArrival") OffsetDateTime planned_arrival,
            @JsonProperty("prognosedArrival") OffsetDateTime prognosed_arrival,
            @JsonProperty("arrivalDelay") Long arrival_delay,
            @JsonProperty("arrivalPlatform") String arrival_platform,
            @JsonProperty("plannedArrivalPlatform") String planned_arrival_platform,
            @JsonProperty("prognosedArrivalPlatform") String prognosed_arrival_platform,
            @JsonProperty("arrivalPrognosisType") PrognosisType arrival_prognosis_type,
            @JsonProperty("stopovers") List<Stopover> stopovers,
            @JsonProperty("remarks") List<Remark> remarks,
            @JsonProperty("walking") Boolean walking,
            @JsonProperty("transfer") Boolean transfer,
            @JsonProperty("distance") Double distance,
            @JsonProperty("public") Boolean public,
            @JsonProperty("reachable") Boolean reachable,
            @JsonProperty("cancelled") Boolean cancelled,
            @JsonProperty("loadFactor") String load_factor,
            @JsonProperty("cycle") Cycle cycle,
            @JsonProperty("alternatives") List<Departure> alternatives,
            @JsonProperty("polyline") Polyline polyline,
            @JsonProperty("price") Price price,
            @JsonProperty("schedule") Long schedule,
            @JsonProperty("currentLocation") Location current_location,
            @JsonProperty("checkin") Boolean checkin,
            @JsonProperty("serviceDays") ServiceDays service_days,
            @JsonProperty("scheduledDays") ServiceDays scheduled_days
    )
    {
        this.trip_id = trip_id;
        this.origin = origin;
        this.destination = destination;
        this.line = line;
        this.direction = direction;
        this.operator = operator;
        this.departure = departure;
        this.planned_departure = planned_departure;
        this.prognosed_departure = prognosed_departure;
        this.departure_delay = departure_delay;
        this.departure_platform = departure_platform;
        this.planned_departure_platform = planned_departure_platform;
        this.prognosed_departure_platform = prognosed_departure_platform;
        this.departure_prognosis_type = departure_prognosis_type;
        this.arrival = arrival;
        this.planned_arrival = planned_arrival;
        this.prognosed_arrival = prognosed_arrival;
        this.arrival_delay = arrival_delay;
        this.arrival_platform = arrival_platform;
        this.planned_arrival_platform = planned_arrival_platform;
        this.prognosed_arrival_platform = prognosed_arrival_platform;
        this.arrival_prognosis_type = arrival_prognosis_type;
        this.stopovers = stopovers;
        this.remarks = remarks;
        this.walking = walking;
        this.transfer = transfer;
        this.distance = distance;
        this.public = public;
        this.reachable = reachable;
        this.cancelled = cancelled;
        this.load_factor = load_factor;
        this.cycle = cycle;
        this.alternatives = alternatives;
        this.polyline = polyline;
        this.price = price;
        this.schedule = schedule;
        this.current_location = current_location;
        this.checkin = checkin;
        this.service_days = service_days;
        this.scheduled_days = scheduled_days;
    }

    public String getTripId() { return trip_id; }

    public Place getOrigin() { return origin; }

    public Place getDestination() { return destination; }

    public Line getLine() { return line; }

    public String getDirection() { return direction; }

    public Operator getOperator() { return operator; }

    public OffsetDateTime getDeparture() { return departure; }

    public OffsetDateTime getPlannedDeparture() { return planned_departure; }

    public OffsetDateTime getPrognosedDeparture() { return prognosed_departure; }

    public Long getDepartureDelay() { return departure_delay; }

    public String getDeparturePlatform() { return departure_platform; }

    public String getPlannedDeparturePlatform() { return planned_departure_platform; }

    public String getPrognosedDeparturePlatform() { return prognosed_departure_platform; }

    public PrognosisType getDeparturePrognosisType() { return departure_prognosis_type; }

    public OffsetDateTime getArrival() { return arrival; }

    public OffsetDateTime getPlannedArrival() { return planned_arrival; }

    public OffsetDateTime getPrognosedArrival() { return prognosed_arrival; }

    public Long getArrivalDelay() { return arrival_delay; }

    public String getArrivalPlatform() { return arrival_platform; }

    public String getPlannedArrivalPlatform() { return planned_arrival_platform; }

    public String getPrognosedArrivalPlatform() { return prognosed_arrival_platform; }

    public PrognosisType getArrivalPrognosisType() { return arrival_prognosis_type; }

    public List<Stopover> getStopovers() { return stopovers; }

    public List<Remark> getRemarks() { return remarks; }

    public Boolean getWalking() { return walking; }

    public Boolean getTransfer() { return transfer; }

    public Double getDistance() { return distance; }

    public Boolean getPublic() { return public; }

    public Boolean getReachable() { return reachable; }

    public Boolean getCancelled() { return cancelled; }

    public String getLoadFactor() { return load_factor; }

    public Cycle getCycle() { return cycle; }

    public List<Departure> getAlternatives() { return alternatives; }

    public Polyline getPolyline() { return polyline; }

    public Price getPrice() { return price; }

    public Long getSchedule() { return schedule; }

    public Location getCurrentLocation() { return current_location; }

    public Boolean getCheckin() { return checkin; }

    public ServiceDays getServiceDays() { return service_days; }

    public ServiceDays getScheduledDays() { return scheduled_days; }

}

/** A public transport line. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Line
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("id")
    private final String id;

    @JsonProperty("name")
    private final String name;

    @JsonProperty("additionalName")
    private final String additional_name;

    @JsonProperty("adminCode")
    private final String admin_code;

    @JsonProperty("fahrtNr")
    private final String fahrt_nr;

    @JsonProperty("product")
    private final String product;

    @JsonProperty("productName")
    private final String product_name;

    @JsonProperty("mode")
    private final Mode mode;

    @JsonProperty("operator")
    private final Operator operator;

    @JsonProperty("express")
    private final Boolean express;

    @JsonProperty("metro")
    private final Boolean metro;

    @JsonProperty("night")
    private final Boolean night;

    @JsonProperty("nr")
    private final Long nr;

    @JsonProperty("symbol")
    private final String symbol;

    @JsonProperty("public")
    private final Boolean public;

    @JsonProperty("directions")
    private final List<String> directions;

    @JsonProperty("routes")
    private final List<String> routes;

    public Line(
            @JsonProperty("id") String id,
            @JsonProperty("name") String name,
            @JsonProperty("additionalName") String additional_name,
            @JsonProperty("adminCode") String admin_code,
            @JsonProperty("fahrtNr") String fahrt_nr,
            @JsonProperty("product") String product,
            @JsonProperty("productName") String product_name,
            @JsonProperty("mode") Mode mode,
            @JsonProperty("operator") Operator operator,
            @JsonProperty("express") Boolean express,
            @JsonProperty("metro") Boolean metro,
            @JsonProperty("night") Boolean night,
            @JsonProperty("nr") Long nr,
            @JsonProperty("symbol") String symbol,
            @JsonProperty("public") Boolean public,
            @JsonProperty("directions") List<String> directions,
            @JsonProperty("routes") List<String> routes
    )
    {
        this.id = id;
        this.name = name;
        this.additional_name = additional_name;
        this.admin_code = admin_code;
        this.fahrt_nr = fahrt_nr;
        this.product = product;
        this.product_name = product_name;
        this.mode = mode;
        this.operator = operator;
        this.express = express;
        this.metro = metro;
        this.night = night;
        this.nr = nr;
        this.symbol = symbol;
        this.public = public;
        this.directions = directions;
        this.routes = routes;
    }

    public String getId() { return id; }

    public String getName() { return name; }

    public String getAdditionalName() { return additional_name; }

    public String getAdminCode() { return admin_code; }

    public String getFahrtNr() { return fahrt_nr; }

    public String getProduct() { return product; }

    public String getProductName() { return product_name; }

    public Mode getMode() { return mode; }

    public Operator getOperator() { return operator; }

    public Boolean getExpress() { return express; }

    public Boolean getMetro() { return metro; }

    public Boolean getNight() { return night; }

    public Long getNr() { return nr; }

    public String getSymbol() { return symbol; }

    public Boolean getPublic() { return public; }

    public List<String> getDirections() { return directions; }

    public List<String> getRoutes() { return routes; }

}

/** A point: POI, address or bare coordinate. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Location
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("id")
    private final String id;

    @JsonProperty("name")
    private final String name;

    @JsonProperty("poi")
    private final Boolean poi;

    @JsonProperty("address")
    private final String address;

    @JsonProperty("latitude")
    private final Double latitude;

    @JsonProperty("longitude")
    private final Double longitude;

    @JsonProperty("altitude")
    private final Double altitude;

    @JsonProperty("distance")
    private final Double distance;

    public Location(
            @JsonProperty("id") String id,
            @JsonProperty("name") String name,
            @JsonProperty("poi") Boolean poi,
            @JsonProperty("address") String address,
            @JsonProperty("latitude") Double latitude,
            @JsonProperty("longitude") Double longitude,
            @JsonProperty("altitude") Double altitude,
            @JsonProperty("distance") Double distance
    )
    {
        this.id = id;
        this.name = name;
        this.poi = poi;
        this.address = address;
        this.latitude = latitude;
        this.longitude = longitude;
        this.altitude = altitude;
        this.distance = distance;
    }

    public String getId() { return id; }

    public String getName() { return name; }

    public Boolean getPoi() { return poi; }

    public String getAddress() { return address; }

    public Double getLatitude() { return latitude; }

    public Double getLongitude() { return longitude; }

    public Double getAltitude() { return altitude; }

    public Double getDistance() { return distance; }

}

/** A vehicle currently moving in the radar area. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Movement
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("direction")
    private final String direction;

    @JsonProperty("tripId")
    private final String trip_id;

    @JsonProperty("line")
    private final Line line;

    @JsonProperty("location")
    private final Location location;

    @JsonProperty("nextStopovers")
    private final List<Stopover> next_stopovers;

    @JsonProperty("frames")
    private final List<Frame> frames;

    @JsonProperty("polyline")
    private final Polyline polyline;

    public Movement(
            @JsonProperty("direction") String direction,
            @JsonProperty("tripId") String trip_id,
            @JsonProperty("line") Line line,
            @JsonProperty("location") Location location,
            @JsonProperty("nextStopovers") List<Stopover> next_stopovers,
            @JsonProperty("frames") List<Frame> frames,
            @JsonProperty("polyline") Polyline polyline
    )
    {
        this.direction = direction;
        this.trip_id = trip_id;
        this.line = line;
        this.location = location;
        this.next_stopovers = next_stopovers;
        this.frames = frames;
        this.polyline = polyline;
    }

    public String getDirection() { return direction; }

    public String getTripId() { return trip_id; }

    public Line getLine() { return line; }

    public Location getLocation() { return location; }

    public List<Stopover> getNextStopovers() { return next_stopovers; }

    public List<Frame> getFrames() { return frames; }

    public Polyline getPolyline() { return polyline; }

}

/** Transit operator. Note: the upstream OpenAPI spec declares Trip.operator as number, but the wire format is an object; parsers must tolerate both. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Operator
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("id")
    private final String id;

    @JsonProperty("name")
    private final String name;

    public Operator(
            @JsonProperty("id") String id,
            @JsonProperty("name") String name
    )
    {
        this.id = id;
        this.name = name;
    }

    public String getId() { return id; }

    public String getName() { return name; }

}

/** GeoJSON FeatureCollection describing a trip/leg shape. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Polyline
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("features")
    private final List<PolylineFeature> features;

    public Polyline(
            @JsonProperty("features") List<PolylineFeature> features
    )
    {
        this.features = features;
    }

    public List<PolylineFeature> getFeatures() { return features; }

}

/** GeoJSON Feature; properties describe the stop located at this position. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class PolylineFeature
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("properties")
    private final LocationResult properties;

    @JsonProperty("geometry")
    private final GeometryPoint geometry;

    public PolylineFeature(
            @JsonProperty("properties") LocationResult properties,
            @JsonProperty("geometry") GeometryPoint geometry
    )
    {
        this.properties = properties;
        this.geometry = geometry;
    }

    public LocationResult getProperties() { return properties; }

    public GeometryPoint getGeometry() { return geometry; }

}

/** Price information for a journey. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Price
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("amount")
    private final Double amount;

    @JsonProperty("currency")
    private final String currency;

    @JsonProperty("hint")
    private final String hint;

    public Price(
            @JsonProperty("amount") Double amount,
            @JsonProperty("currency") String currency,
            @JsonProperty("hint") String hint
    )
    {
        this.amount = amount;
        this.currency = currency;
        this.hint = hint;
    }

    public Double getAmount() { return amount; }

    public String getCurrency() { return currency; }

    public String getHint() { return hint; }

}

/** Reachability result: travel duration and reachable stations. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class ReachableDuration
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("duration")
    private final Long duration;

    @JsonProperty("stations")
    private final List<LocationResult> stations;

    public ReachableDuration(
            @JsonProperty("duration") Long duration,
            @JsonProperty("stations") List<LocationResult> stations
    )
    {
        this.duration = duration;
        this.stations = stations;
    }

    public Long getDuration() { return duration; }

    public List<LocationResult> getStations() { return stations; }

}

/** Hint, status or warning attached to journeys/legs/departures/trips/stops. Merged model of FPTF hint/status/warning. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Remark
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("type")
    private final RemarkKind kind;

    @JsonProperty("code")
    private final String code;

    @JsonProperty("summary")
    private final String summary;

    @JsonProperty("text")
    private final String text;

    @JsonProperty("tripId")
    private final String trip_id;

    @JsonProperty("id")
    private final String id;

    @JsonProperty("priority")
    private final Long priority;

    @JsonProperty("category")
    private final String category;

    @JsonProperty("products")
    private final Products products;

    @JsonProperty("company")
    private final String company;

    @JsonProperty("validFrom")
    private final OffsetDateTime valid_from;

    @JsonProperty("validUntil")
    private final OffsetDateTime valid_until;

    @JsonProperty("modified")
    private final OffsetDateTime modified;

    @JsonProperty("affectedLines")
    private final List<Line> affected_lines;

    @JsonProperty("fromStops")
    private final List<LocationResult> from_stops;

    @JsonProperty("toStops")
    private final List<LocationResult> to_stops;

    public Remark(
            @JsonProperty("type") RemarkKind kind,
            @JsonProperty("code") String code,
            @JsonProperty("summary") String summary,
            @JsonProperty("text") String text,
            @JsonProperty("tripId") String trip_id,
            @JsonProperty("id") String id,
            @JsonProperty("priority") Long priority,
            @JsonProperty("category") String category,
            @JsonProperty("products") Products products,
            @JsonProperty("company") String company,
            @JsonProperty("validFrom") OffsetDateTime valid_from,
            @JsonProperty("validUntil") OffsetDateTime valid_until,
            @JsonProperty("modified") OffsetDateTime modified,
            @JsonProperty("affectedLines") List<Line> affected_lines,
            @JsonProperty("fromStops") List<LocationResult> from_stops,
            @JsonProperty("toStops") List<LocationResult> to_stops
    )
    {
        this.kind = kind;
        this.code = code;
        this.summary = summary;
        this.text = text;
        this.trip_id = trip_id;
        this.id = id;
        this.priority = priority;
        this.category = category;
        this.products = products;
        this.company = company;
        this.valid_from = valid_from;
        this.valid_until = valid_until;
        this.modified = modified;
        this.affected_lines = affected_lines;
        this.from_stops = from_stops;
        this.to_stops = to_stops;
    }

    public RemarkKind getKind() { return kind; }

    public String getCode() { return code; }

    public String getSummary() { return summary; }

    public String getText() { return text; }

    public String getTripId() { return trip_id; }

    public String getId() { return id; }

    public Long getPriority() { return priority; }

    public String getCategory() { return category; }

    public Products getProducts() { return products; }

    public String getCompany() { return company; }

    public OffsetDateTime getValidFrom() { return valid_from; }

    public OffsetDateTime getValidUntil() { return valid_until; }

    public OffsetDateTime getModified() { return modified; }

    public List<Line> getAffectedLines() { return affected_lines; }

    public List<LocationResult> getFromStops() { return from_stops; }

    public List<LocationResult> getToStops() { return to_stops; }

}

/** A larger station area possibly containing multiple stops. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Station
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("id")
    private final String id;

    @JsonProperty("name")
    private final String name;

    @JsonProperty("station")
    private final Station station;

    @JsonProperty("location")
    private final Location location;

    @JsonProperty("products")
    private final Products products;

    @JsonProperty("lines")
    private final List<Line> lines;

    @JsonProperty("isMeta")
    private final Boolean is_meta;

    @JsonProperty("regions")
    private final List<String> regions;

    @JsonProperty("facilities")
    private final Map<String, String> facilities;

    @JsonProperty("reisezentrumOpeningHours")
    private final OpeningHours opening_hours;

    @JsonProperty("stops")
    private final List<LocationResult> stops;

    @JsonProperty("entrances")
    private final List<Location> entrances;

    @JsonProperty("transitAuthority")
    private final String transit_authority;

    @JsonProperty("distance")
    private final Double distance;

    public Station(
            @JsonProperty("id") String id,
            @JsonProperty("name") String name,
            @JsonProperty("station") Station station,
            @JsonProperty("location") Location location,
            @JsonProperty("products") Products products,
            @JsonProperty("lines") List<Line> lines,
            @JsonProperty("isMeta") Boolean is_meta,
            @JsonProperty("regions") List<String> regions,
            @JsonProperty("facilities") Map<String, String> facilities,
            @JsonProperty("reisezentrumOpeningHours") OpeningHours opening_hours,
            @JsonProperty("stops") List<LocationResult> stops,
            @JsonProperty("entrances") List<Location> entrances,
            @JsonProperty("transitAuthority") String transit_authority,
            @JsonProperty("distance") Double distance
    )
    {
        this.id = id;
        this.name = name;
        this.station = station;
        this.location = location;
        this.products = products;
        this.lines = lines;
        this.is_meta = is_meta;
        this.regions = regions;
        this.facilities = facilities;
        this.opening_hours = opening_hours;
        this.stops = stops;
        this.entrances = entrances;
        this.transit_authority = transit_authority;
        this.distance = distance;
    }

    public String getId() { return id; }

    public String getName() { return name; }

    public Station getStation() { return station; }

    public Location getLocation() { return location; }

    public Products getProducts() { return products; }

    public List<Line> getLines() { return lines; }

    public Boolean getIsMeta() { return is_meta; }

    public List<String> getRegions() { return regions; }

    public Map<String, String> getFacilities() { return facilities; }

    public OpeningHours getOpeningHours() { return opening_hours; }

    public List<LocationResult> getStops() { return stops; }

    public List<Location> getEntrances() { return entrances; }

    public String getTransitAuthority() { return transit_authority; }

    public Double getDistance() { return distance; }

}

/** A single physical stop (platform, bus stop sign, ...). */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Stop
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("id")
    private final String id;

    @JsonProperty("name")
    private final String name;

    @JsonProperty("station")
    private final Station station;

    @JsonProperty("location")
    private final Location location;

    @JsonProperty("products")
    private final Products products;

    @JsonProperty("ids")
    private final Ids ids;

    @JsonProperty("lines")
    private final List<Line> lines;

    @JsonProperty("entrances")
    private final List<Location> entrances;

    @JsonProperty("isMeta")
    private final Boolean is_meta;

    @JsonProperty("reisezentrumOpeningHours")
    private final OpeningHours opening_hours;

    @JsonProperty("loadFactor")
    private final String load_factor;

    @JsonProperty("transitAuthority")
    private final String transit_authority;

    @JsonProperty("distance")
    private final Double distance;

    public Stop(
            @JsonProperty("id") String id,
            @JsonProperty("name") String name,
            @JsonProperty("station") Station station,
            @JsonProperty("location") Location location,
            @JsonProperty("products") Products products,
            @JsonProperty("ids") Ids ids,
            @JsonProperty("lines") List<Line> lines,
            @JsonProperty("entrances") List<Location> entrances,
            @JsonProperty("isMeta") Boolean is_meta,
            @JsonProperty("reisezentrumOpeningHours") OpeningHours opening_hours,
            @JsonProperty("loadFactor") String load_factor,
            @JsonProperty("transitAuthority") String transit_authority,
            @JsonProperty("distance") Double distance
    )
    {
        this.id = id;
        this.name = name;
        this.station = station;
        this.location = location;
        this.products = products;
        this.ids = ids;
        this.lines = lines;
        this.entrances = entrances;
        this.is_meta = is_meta;
        this.opening_hours = opening_hours;
        this.load_factor = load_factor;
        this.transit_authority = transit_authority;
        this.distance = distance;
    }

    public String getId() { return id; }

    public String getName() { return name; }

    public Station getStation() { return station; }

    public Location getLocation() { return location; }

    public Products getProducts() { return products; }

    public Ids getIds() { return ids; }

    public List<Line> getLines() { return lines; }

    public List<Location> getEntrances() { return entrances; }

    public Boolean getIsMeta() { return is_meta; }

    public OpeningHours getOpeningHours() { return opening_hours; }

    public String getLoadFactor() { return load_factor; }

    public String getTransitAuthority() { return transit_authority; }

    public Double getDistance() { return distance; }

}

/** A vehicle stopping at a stop at specific times. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Stopover
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("stop")
    private final StopOrStation stop;

    @JsonProperty("arrival")
    private final OffsetDateTime arrival;

    @JsonProperty("plannedArrival")
    private final OffsetDateTime planned_arrival;

    @JsonProperty("prognosedArrival")
    private final OffsetDateTime prognosed_arrival;

    @JsonProperty("arrivalDelay")
    private final Long arrival_delay;

    @JsonProperty("arrivalPlatform")
    private final String arrival_platform;

    @JsonProperty("plannedArrivalPlatform")
    private final String planned_arrival_platform;

    @JsonProperty("prognosedArrivalPlatform")
    private final String prognosed_arrival_platform;

    @JsonProperty("arrivalPrognosisType")
    private final PrognosisType arrival_prognosis_type;

    @JsonProperty("departure")
    private final OffsetDateTime departure;

    @JsonProperty("plannedDeparture")
    private final OffsetDateTime planned_departure;

    @JsonProperty("prognosedDeparture")
    private final OffsetDateTime prognosed_departure;

    @JsonProperty("departureDelay")
    private final Long departure_delay;

    @JsonProperty("departurePlatform")
    private final String departure_platform;

    @JsonProperty("plannedDeparturePlatform")
    private final String planned_departure_platform;

    @JsonProperty("prognosedDeparturePlatform")
    private final String prognosed_departure_platform;

    @JsonProperty("departurePrognosisType")
    private final PrognosisType departure_prognosis_type;

    @JsonProperty("remarks")
    private final List<Remark> remarks;

    @JsonProperty("passBy")
    private final Boolean pass_by;

    @JsonProperty("cancelled")
    private final Boolean cancelled;

    @JsonProperty("additional")
    private final Boolean additional;

    public Stopover(
            @JsonProperty("stop") StopOrStation stop,
            @JsonProperty("arrival") OffsetDateTime arrival,
            @JsonProperty("plannedArrival") OffsetDateTime planned_arrival,
            @JsonProperty("prognosedArrival") OffsetDateTime prognosed_arrival,
            @JsonProperty("arrivalDelay") Long arrival_delay,
            @JsonProperty("arrivalPlatform") String arrival_platform,
            @JsonProperty("plannedArrivalPlatform") String planned_arrival_platform,
            @JsonProperty("prognosedArrivalPlatform") String prognosed_arrival_platform,
            @JsonProperty("arrivalPrognosisType") PrognosisType arrival_prognosis_type,
            @JsonProperty("departure") OffsetDateTime departure,
            @JsonProperty("plannedDeparture") OffsetDateTime planned_departure,
            @JsonProperty("prognosedDeparture") OffsetDateTime prognosed_departure,
            @JsonProperty("departureDelay") Long departure_delay,
            @JsonProperty("departurePlatform") String departure_platform,
            @JsonProperty("plannedDeparturePlatform") String planned_departure_platform,
            @JsonProperty("prognosedDeparturePlatform") String prognosed_departure_platform,
            @JsonProperty("departurePrognosisType") PrognosisType departure_prognosis_type,
            @JsonProperty("remarks") List<Remark> remarks,
            @JsonProperty("passBy") Boolean pass_by,
            @JsonProperty("cancelled") Boolean cancelled,
            @JsonProperty("additional") Boolean additional
    )
    {
        this.stop = stop;
        this.arrival = arrival;
        this.planned_arrival = planned_arrival;
        this.prognosed_arrival = prognosed_arrival;
        this.arrival_delay = arrival_delay;
        this.arrival_platform = arrival_platform;
        this.planned_arrival_platform = planned_arrival_platform;
        this.prognosed_arrival_platform = prognosed_arrival_platform;
        this.arrival_prognosis_type = arrival_prognosis_type;
        this.departure = departure;
        this.planned_departure = planned_departure;
        this.prognosed_departure = prognosed_departure;
        this.departure_delay = departure_delay;
        this.departure_platform = departure_platform;
        this.planned_departure_platform = planned_departure_platform;
        this.prognosed_departure_platform = prognosed_departure_platform;
        this.departure_prognosis_type = departure_prognosis_type;
        this.remarks = remarks;
        this.pass_by = pass_by;
        this.cancelled = cancelled;
        this.additional = additional;
    }

    public StopOrStation getStop() { return stop; }

    public OffsetDateTime getArrival() { return arrival; }

    public OffsetDateTime getPlannedArrival() { return planned_arrival; }

    public OffsetDateTime getPrognosedArrival() { return prognosed_arrival; }

    public Long getArrivalDelay() { return arrival_delay; }

    public String getArrivalPlatform() { return arrival_platform; }

    public String getPlannedArrivalPlatform() { return planned_arrival_platform; }

    public String getPrognosedArrivalPlatform() { return prognosed_arrival_platform; }

    public PrognosisType getArrivalPrognosisType() { return arrival_prognosis_type; }

    public OffsetDateTime getDeparture() { return departure; }

    public OffsetDateTime getPlannedDeparture() { return planned_departure; }

    public OffsetDateTime getPrognosedDeparture() { return prognosed_departure; }

    public Long getDepartureDelay() { return departure_delay; }

    public String getDeparturePlatform() { return departure_platform; }

    public String getPlannedDeparturePlatform() { return planned_departure_platform; }

    public String getPrognosedDeparturePlatform() { return prognosed_departure_platform; }

    public PrognosisType getDeparturePrognosisType() { return departure_prognosis_type; }

    public List<Remark> getRemarks() { return remarks; }

    public Boolean getPassBy() { return pass_by; }

    public Boolean getCancelled() { return cancelled; }

    public Boolean getAdditional() { return additional; }

}

/** A specific vehicle stopping at a set of stops at specific times. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class Trip
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("id")
    private final String id;

    @JsonProperty("origin")
    private final Place origin;

    @JsonProperty("destination")
    private final Place destination;

    @JsonProperty("line")
    private final Line line;

    @JsonProperty("direction")
    private final String direction;

    @JsonProperty("operator")
    private final Operator operator;

    @JsonProperty("departure")
    private final OffsetDateTime departure;

    @JsonProperty("plannedDeparture")
    private final OffsetDateTime planned_departure;

    @JsonProperty("prognosedDeparture")
    private final OffsetDateTime prognosed_departure;

    @JsonProperty("departureDelay")
    private final Long departure_delay;

    @JsonProperty("departurePlatform")
    private final String departure_platform;

    @JsonProperty("plannedDeparturePlatform")
    private final String planned_departure_platform;

    @JsonProperty("prognosedDeparturePlatform")
    private final String prognosed_departure_platform;

    @JsonProperty("departurePrognosisType")
    private final PrognosisType departure_prognosis_type;

    @JsonProperty("arrival")
    private final OffsetDateTime arrival;

    @JsonProperty("plannedArrival")
    private final OffsetDateTime planned_arrival;

    @JsonProperty("prognosedArrival")
    private final OffsetDateTime prognosed_arrival;

    @JsonProperty("arrivalDelay")
    private final Long arrival_delay;

    @JsonProperty("arrivalPlatform")
    private final String arrival_platform;

    @JsonProperty("plannedArrivalPlatform")
    private final String planned_arrival_platform;

    @JsonProperty("prognosedArrivalPlatform")
    private final String prognosed_arrival_platform;

    @JsonProperty("arrivalPrognosisType")
    private final PrognosisType arrival_prognosis_type;

    @JsonProperty("stopovers")
    private final List<Stopover> stopovers;

    @JsonProperty("remarks")
    private final List<Remark> remarks;

    @JsonProperty("walking")
    private final Boolean walking;

    @JsonProperty("transfer")
    private final Boolean transfer;

    @JsonProperty("distance")
    private final Double distance;

    @JsonProperty("public")
    private final Boolean public;

    @JsonProperty("cancelled")
    private final Boolean cancelled;

    @JsonProperty("loadFactor")
    private final String load_factor;

    @JsonProperty("cycle")
    private final Cycle cycle;

    @JsonProperty("alternatives")
    private final List<Departure> alternatives;

    @JsonProperty("polyline")
    private final Polyline polyline;

    @JsonProperty("price")
    private final Price price;

    @JsonProperty("schedule")
    private final Long schedule;

    @JsonProperty("currentLocation")
    private final Location current_location;

    @JsonProperty("checkin")
    private final Boolean checkin;

    @JsonProperty("serviceDays")
    private final ServiceDays service_days;

    @JsonProperty("scheduledDays")
    private final ServiceDays scheduled_days;

    public Trip(
            @JsonProperty("id") String id,
            @JsonProperty("origin") Place origin,
            @JsonProperty("destination") Place destination,
            @JsonProperty("line") Line line,
            @JsonProperty("direction") String direction,
            @JsonProperty("operator") Operator operator,
            @JsonProperty("departure") OffsetDateTime departure,
            @JsonProperty("plannedDeparture") OffsetDateTime planned_departure,
            @JsonProperty("prognosedDeparture") OffsetDateTime prognosed_departure,
            @JsonProperty("departureDelay") Long departure_delay,
            @JsonProperty("departurePlatform") String departure_platform,
            @JsonProperty("plannedDeparturePlatform") String planned_departure_platform,
            @JsonProperty("prognosedDeparturePlatform") String prognosed_departure_platform,
            @JsonProperty("departurePrognosisType") PrognosisType departure_prognosis_type,
            @JsonProperty("arrival") OffsetDateTime arrival,
            @JsonProperty("plannedArrival") OffsetDateTime planned_arrival,
            @JsonProperty("prognosedArrival") OffsetDateTime prognosed_arrival,
            @JsonProperty("arrivalDelay") Long arrival_delay,
            @JsonProperty("arrivalPlatform") String arrival_platform,
            @JsonProperty("plannedArrivalPlatform") String planned_arrival_platform,
            @JsonProperty("prognosedArrivalPlatform") String prognosed_arrival_platform,
            @JsonProperty("arrivalPrognosisType") PrognosisType arrival_prognosis_type,
            @JsonProperty("stopovers") List<Stopover> stopovers,
            @JsonProperty("remarks") List<Remark> remarks,
            @JsonProperty("walking") Boolean walking,
            @JsonProperty("transfer") Boolean transfer,
            @JsonProperty("distance") Double distance,
            @JsonProperty("public") Boolean public,
            @JsonProperty("cancelled") Boolean cancelled,
            @JsonProperty("loadFactor") String load_factor,
            @JsonProperty("cycle") Cycle cycle,
            @JsonProperty("alternatives") List<Departure> alternatives,
            @JsonProperty("polyline") Polyline polyline,
            @JsonProperty("price") Price price,
            @JsonProperty("schedule") Long schedule,
            @JsonProperty("currentLocation") Location current_location,
            @JsonProperty("checkin") Boolean checkin,
            @JsonProperty("serviceDays") ServiceDays service_days,
            @JsonProperty("scheduledDays") ServiceDays scheduled_days
    )
    {
        this.id = id;
        this.origin = origin;
        this.destination = destination;
        this.line = line;
        this.direction = direction;
        this.operator = operator;
        this.departure = departure;
        this.planned_departure = planned_departure;
        this.prognosed_departure = prognosed_departure;
        this.departure_delay = departure_delay;
        this.departure_platform = departure_platform;
        this.planned_departure_platform = planned_departure_platform;
        this.prognosed_departure_platform = prognosed_departure_platform;
        this.departure_prognosis_type = departure_prognosis_type;
        this.arrival = arrival;
        this.planned_arrival = planned_arrival;
        this.prognosed_arrival = prognosed_arrival;
        this.arrival_delay = arrival_delay;
        this.arrival_platform = arrival_platform;
        this.planned_arrival_platform = planned_arrival_platform;
        this.prognosed_arrival_platform = prognosed_arrival_platform;
        this.arrival_prognosis_type = arrival_prognosis_type;
        this.stopovers = stopovers;
        this.remarks = remarks;
        this.walking = walking;
        this.transfer = transfer;
        this.distance = distance;
        this.public = public;
        this.cancelled = cancelled;
        this.load_factor = load_factor;
        this.cycle = cycle;
        this.alternatives = alternatives;
        this.polyline = polyline;
        this.price = price;
        this.schedule = schedule;
        this.current_location = current_location;
        this.checkin = checkin;
        this.service_days = service_days;
        this.scheduled_days = scheduled_days;
    }

    public String getId() { return id; }

    public Place getOrigin() { return origin; }

    public Place getDestination() { return destination; }

    public Line getLine() { return line; }

    public String getDirection() { return direction; }

    public Operator getOperator() { return operator; }

    public OffsetDateTime getDeparture() { return departure; }

    public OffsetDateTime getPlannedDeparture() { return planned_departure; }

    public OffsetDateTime getPrognosedDeparture() { return prognosed_departure; }

    public Long getDepartureDelay() { return departure_delay; }

    public String getDeparturePlatform() { return departure_platform; }

    public String getPlannedDeparturePlatform() { return planned_departure_platform; }

    public String getPrognosedDeparturePlatform() { return prognosed_departure_platform; }

    public PrognosisType getDeparturePrognosisType() { return departure_prognosis_type; }

    public OffsetDateTime getArrival() { return arrival; }

    public OffsetDateTime getPlannedArrival() { return planned_arrival; }

    public OffsetDateTime getPrognosedArrival() { return prognosed_arrival; }

    public Long getArrivalDelay() { return arrival_delay; }

    public String getArrivalPlatform() { return arrival_platform; }

    public String getPlannedArrivalPlatform() { return planned_arrival_platform; }

    public String getPrognosedArrivalPlatform() { return prognosed_arrival_platform; }

    public PrognosisType getArrivalPrognosisType() { return arrival_prognosis_type; }

    public List<Stopover> getStopovers() { return stopovers; }

    public List<Remark> getRemarks() { return remarks; }

    public Boolean getWalking() { return walking; }

    public Boolean getTransfer() { return transfer; }

    public Double getDistance() { return distance; }

    public Boolean getPublic() { return public; }

    public Boolean getCancelled() { return cancelled; }

    public String getLoadFactor() { return load_factor; }

    public Cycle getCycle() { return cycle; }

    public List<Departure> getAlternatives() { return alternatives; }

    public Polyline getPolyline() { return polyline; }

    public Price getPrice() { return price; }

    public Long getSchedule() { return schedule; }

    public Location getCurrentLocation() { return current_location; }

    public Boolean getCheckin() { return checkin; }

    public ServiceDays getServiceDays() { return service_days; }

    public ServiceDays getScheduledDays() { return scheduled_days; }

}

/** Response of GET /stops/{id}/arrivals. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class ArrivalsResponse
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("arrivals")
    private final List<Departure> arrivals;

    @JsonProperty("realtimeDataUpdatedAt")
    private final Long realtime_data_updated_at;

    public ArrivalsResponse(
            @JsonProperty("arrivals") List<Departure> arrivals,
            @JsonProperty("realtimeDataUpdatedAt") Long realtime_data_updated_at
    )
    {
        this.arrivals = arrivals;
        this.realtime_data_updated_at = realtime_data_updated_at;
    }

    public List<Departure> getArrivals() { return arrivals; }

    public Long getRealtimeDataUpdatedAt() { return realtime_data_updated_at; }

}

/** Response of GET /stops/{id}/departures. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class DeparturesResponse
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("departures")
    private final List<Departure> departures;

    @JsonProperty("realtimeDataUpdatedAt")
    private final Long realtime_data_updated_at;

    public DeparturesResponse(
            @JsonProperty("departures") List<Departure> departures,
            @JsonProperty("realtimeDataUpdatedAt") Long realtime_data_updated_at
    )
    {
        this.departures = departures;
        this.realtime_data_updated_at = realtime_data_updated_at;
    }

    public List<Departure> getDepartures() { return departures; }

    public Long getRealtimeDataUpdatedAt() { return realtime_data_updated_at; }

}

/** Response of GET /journeys/{ref}. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class JourneyResponse
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("journey")
    private final Journey journey;

    @JsonProperty("realtimeDataUpdatedAt")
    private final Long realtime_data_updated_at;

    public JourneyResponse(
            @JsonProperty("journey") Journey journey,
            @JsonProperty("realtimeDataUpdatedAt") Long realtime_data_updated_at
    )
    {
        this.journey = journey;
        this.realtime_data_updated_at = realtime_data_updated_at;
    }

    public Journey getJourney() { return journey; }

    public Long getRealtimeDataUpdatedAt() { return realtime_data_updated_at; }

}

/** Response of GET /journeys. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class JourneysResponse
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("journeys")
    private final List<Journey> journeys;

    @JsonProperty("earlierRef")
    private final String earlier_ref;

    @JsonProperty("laterRef")
    private final String later_ref;

    @JsonProperty("realtimeDataUpdatedAt")
    private final Long realtime_data_updated_at;

    public JourneysResponse(
            @JsonProperty("journeys") List<Journey> journeys,
            @JsonProperty("earlierRef") String earlier_ref,
            @JsonProperty("laterRef") String later_ref,
            @JsonProperty("realtimeDataUpdatedAt") Long realtime_data_updated_at
    )
    {
        this.journeys = journeys;
        this.earlier_ref = earlier_ref;
        this.later_ref = later_ref;
        this.realtime_data_updated_at = realtime_data_updated_at;
    }

    public List<Journey> getJourneys() { return journeys; }

    public String getEarlierRef() { return earlier_ref; }

    public String getLaterRef() { return later_ref; }

    public Long getRealtimeDataUpdatedAt() { return realtime_data_updated_at; }

}

/** Response of GET /radar. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class RadarResponse
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("movements")
    private final List<Movement> movements;

    @JsonProperty("realtimeDataUpdatedAt")
    private final Long realtime_data_updated_at;

    public RadarResponse(
            @JsonProperty("movements") List<Movement> movements,
            @JsonProperty("realtimeDataUpdatedAt") Long realtime_data_updated_at
    )
    {
        this.movements = movements;
        this.realtime_data_updated_at = realtime_data_updated_at;
    }

    public List<Movement> getMovements() { return movements; }

    public Long getRealtimeDataUpdatedAt() { return realtime_data_updated_at; }

}

/** Response of GET /stops/reachable-from. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class ReachableFromResponse
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("reachable")
    private final List<ReachableDuration> reachable;

    @JsonProperty("realtimeDataUpdatedAt")
    private final Long realtime_data_updated_at;

    public ReachableFromResponse(
            @JsonProperty("reachable") List<ReachableDuration> reachable,
            @JsonProperty("realtimeDataUpdatedAt") Long realtime_data_updated_at
    )
    {
        this.reachable = reachable;
        this.realtime_data_updated_at = realtime_data_updated_at;
    }

    public List<ReachableDuration> getReachable() { return reachable; }

    public Long getRealtimeDataUpdatedAt() { return realtime_data_updated_at; }

}

/** Response of GET /trips/{id}. */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class TripResponse
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("trip")
    private final Trip trip;

    @JsonProperty("realtimeDataUpdatedAt")
    private final Long realtime_data_updated_at;

    public TripResponse(
            @JsonProperty("trip") Trip trip,
            @JsonProperty("realtimeDataUpdatedAt") Long realtime_data_updated_at
    )
    {
        this.trip = trip;
        this.realtime_data_updated_at = realtime_data_updated_at;
    }

    public Trip getTrip() { return trip; }

    public Long getRealtimeDataUpdatedAt() { return realtime_data_updated_at; }

}

/** Response of GET /trips (trips by name). */
@JsonIgnoreProperties(ignoreUnknown = true)
public final class TripsResponse
{
    private final Map<String, Object> unknownFields = new HashMap<>();

    @JsonAnyGetter
    public Map<String, Object> getUnknownFields() { return unknownFields; }

    @JsonAnySetter
    void setUnknownField(String key, Object value) { unknownFields.put(key, value); }

    @JsonProperty("trips")
    private final List<Trip> trips;

    @JsonProperty("realtimeDataUpdatedAt")
    private final Long realtime_data_updated_at;

    public TripsResponse(
            @JsonProperty("trips") List<Trip> trips,
            @JsonProperty("realtimeDataUpdatedAt") Long realtime_data_updated_at
    )
    {
        this.trips = trips;
        this.realtime_data_updated_at = realtime_data_updated_at;
    }

    public List<Trip> getTrips() { return trips; }

    public Long getRealtimeDataUpdatedAt() { return realtime_data_updated_at; }

}

