// <auto-generated>
// Code generated by transport-rest-gen. DO NOT EDIT.
// </auto-generated>

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable
using Ids = IReadOnlyDictionary<string, string>;
using OpeningHours = IReadOnlyDictionary<string, string>;
using Products = IReadOnlyDictionary<string, bool>;
using ServiceDays = IReadOnlyDictionary<string, bool>;

namespace TransportRest.Models;

/// <summary>Accessibility Open enum: unknown wire values are valid strings.</summary>
public static class Accessibility
{
    /// <summary>Wire value <c>partial</c>.</summary>
    public const string partial = "partial";
    /// <summary>Wire value <c>complete</c>.</summary>
    public const string complete = "complete";
}

/// <summary>AgeGroup Open enum: unknown wire values are valid strings.</summary>
public static class AgeGroup
{
    /// <summary>Wire value <c>B</c>.</summary>
    public const string B = "B";
    /// <summary>Wire value <c>E</c>.</summary>
    public const string E = "E";
    /// <summary>Wire value <c>K</c>.</summary>
    public const string K = "K";
    /// <summary>Wire value <c>S</c>.</summary>
    public const string S = "S";
    /// <summary>Wire value <c>Y</c>.</summary>
    public const string Y = "Y";
}

/// <summary>db-vendo backend profile selector of the DB instance. Open enum: unknown wire values are valid strings.</summary>
public static class DbProfile
{
    /// <summary>Wire value <c>dbnav</c>.</summary>
    public const string dbnav = "dbnav";
    /// <summary>Wire value <c>db</c>.</summary>
    public const string db = "db";
    /// <summary>Wire value <c>dbweb</c>.</summary>
    public const string dbweb = "dbweb";
}

/// <summary>LoyaltyCard Open enum: unknown wire values are valid strings.</summary>
public static class LoyaltyCard
{
    /// <summary>Wire value <c>bahncard-1st-25</c>.</summary>
    public const string bahncard_1st_25 = "bahncard-1st-25";
    /// <summary>Wire value <c>bahncard-2nd-25</c>.</summary>
    public const string bahncard_2nd_25 = "bahncard-2nd-25";
    /// <summary>Wire value <c>bahncard-1st-50</c>.</summary>
    public const string bahncard_1st_50 = "bahncard-1st-50";
    /// <summary>Wire value <c>bahncard-2nd-50</c>.</summary>
    public const string bahncard_2nd_50 = "bahncard-2nd-50";
    /// <summary>Wire value <c>bahncard-1st-100</c>.</summary>
    public const string bahncard_1st_100 = "bahncard-1st-100";
    /// <summary>Wire value <c>bahncard-2nd-100</c>.</summary>
    public const string bahncard_2nd_100 = "bahncard-2nd-100";
    /// <summary>Wire value <c>vorteilscard</c>.</summary>
    public const string vorteilscard = "vorteilscard";
    /// <summary>Wire value <c>halbtaxabo</c>.</summary>
    public const string halbtaxabo = "halbtaxabo";
    /// <summary>Wire value <c>generalabonnement-1st</c>.</summary>
    public const string generalabonnement_1st = "generalabonnement-1st";
    /// <summary>Wire value <c>generalabonnement-2nd</c>.</summary>
    public const string generalabonnement_2nd = "generalabonnement-2nd";
    /// <summary>Wire value <c>nl-40</c>.</summary>
    public const string nl_40 = "nl-40";
    /// <summary>Wire value <c>at-klimaticket</c>.</summary>
    public const string at_klimaticket = "at-klimaticket";
}

/// <summary>Means of transport mode (FPTF). Open enum: unknown wire values map to the fallback variant. Open enum: unknown wire values are valid strings.</summary>
public static class Mode
{
    /// <summary>Wire value <c>aircraft</c>.</summary>
    public const string aircraft = "aircraft";
    /// <summary>Wire value <c>bicycle</c>.</summary>
    public const string bicycle = "bicycle";
    /// <summary>Wire value <c>bus</c>.</summary>
    public const string bus = "bus";
    /// <summary>Wire value <c>car</c>.</summary>
    public const string car = "car";
    /// <summary>Wire value <c>gondola</c>.</summary>
    public const string gondola = "gondola";
    /// <summary>Wire value <c>taxi</c>.</summary>
    public const string taxi = "taxi";
    /// <summary>Wire value <c>train</c>.</summary>
    public const string train = "train";
    /// <summary>Wire value <c>walking</c>.</summary>
    public const string walking = "walking";
    /// <summary>Wire value <c>watercraft</c>.</summary>
    public const string watercraft = "watercraft";
}

/// <summary>Reliability class of a prognosis. Open enum: unknown wire values are valid strings.</summary>
public static class PrognosisType
{
    /// <summary>Wire value <c>calculated</c>.</summary>
    public const string calculated = "calculated";
    /// <summary>Wire value <c>prognosed</c>.</summary>
    public const string prognosed = "prognosed";
}

/// <summary>Discriminator of remark objects; FPTF hint/status/warning are merged into one model. Open enum: unknown wire values are valid strings.</summary>
public static class RemarkKind
{
    /// <summary>Wire value <c>hint</c>.</summary>
    public const string hint = "hint";
    /// <summary>Wire value <c>status</c>.</summary>
    public const string status = "status";
    /// <summary>Wire value <c>warning</c>.</summary>
    public const string warning = "warning";
    /// <summary>Wire value <c>foreign-id</c>.</summary>
    public const string foreign_id = "foreign-id";
    /// <summary>Wire value <c>local-fare-zone</c>.</summary>
    public const string local_fare_zone = "local-fare-zone";
    /// <summary>Wire value <c>stop-dhid</c>.</summary>
    public const string stop_dhid = "stop-dhid";
    /// <summary>Wire value <c>stop-website</c>.</summary>
    public const string stop_website = "stop-website";
    /// <summary>Wire value <c>transit-authority</c>.</summary>
    public const string transit_authority = "transit-authority";
}

/// <summary>REALTIME is the default and excludes cancelled journeys; HYBRID includes them and fully supports pagination. Open enum: unknown wire values are valid strings.</summary>
public static class RoutingMode
{
    /// <summary>Wire value <c>FULL</c>.</summary>
    public const string FULL = "FULL";
    /// <summary>Wire value <c>HYBRID</c>.</summary>
    public const string HYBRID = "HYBRID";
    /// <summary>Wire value <c>INFOS</c>.</summary>
    public const string INFOS = "INFOS";
    /// <summary>Wire value <c>OFF</c>.</summary>
    public const string OFF = "OFF";
    /// <summary>Wire value <c>REALTIME</c>.</summary>
    public const string REALTIME = "REALTIME";
    /// <summary>Wire value <c>SERVER_DEFAULT</c>.</summary>
    public const string SERVER_DEFAULT = "SERVER_DEFAULT";
}

/// <summary>WalkingSpeed Open enum: unknown wire values are valid strings.</summary>
public static class WalkingSpeed
{
    /// <summary>Wire value <c>slow</c>.</summary>
    public const string slow = "slow";
    /// <summary>Wire value <c>normal</c>.</summary>
    public const string normal = "normal";
    /// <summary>Wire value <c>fast</c>.</summary>
    public const string fast = "fast";
}

/// <summary>LocationResult - tagged union (stop/station/location or unknown type); kept as raw JSON.</summary>
public sealed class LocationResult
{
    public LocationResult(JsonElement raw) { Raw = raw; }

    public JsonElement Raw { get; }
}

/// <summary>Place - tagged union (stop/station/location or unknown type); kept as raw JSON.</summary>
public sealed class Place
{
    public Place(JsonElement raw) { Raw = raw; }

    public JsonElement Raw { get; }
}

/// <summary>StopOrStation - tagged union (stop/station/location or unknown type); kept as raw JSON.</summary>
public sealed class StopOrStation
{
    public StopOrStation(JsonElement raw) { Raw = raw; }

    public JsonElement Raw { get; }
}

/// <summary>Cycle times of a line/trip in minutes.</summary>
public class Cycle
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("min")]
    public long? Min { get; set; }

    [JsonPropertyName("max")]
    public long? Max { get; set; }

    [JsonPropertyName("nr")]
    public long? Nr { get; set; }

}

/// <summary>A departure or arrival board entry (OpenAPI schema name: Alternative).</summary>
public class Departure
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("tripId")]
    public string TripId { get; set; }

    [JsonPropertyName("stop")]
    public StopOrStation Stop { get; set; }

    /// <summary>Current vehicle position (radar).</summary>
    [JsonPropertyName("location")]
    public Location Location { get; set; }

    [JsonPropertyName("line")]
    public Line Line { get; set; }

    [JsonPropertyName("direction")]
    public string Direction { get; set; }

    /// <summary>Origin of the vehicle (arrivals boards).</summary>
    [JsonPropertyName("provenance")]
    public string Provenance { get; set; }

    [JsonPropertyName("origin")]
    public Place Origin { get; set; }

    [JsonPropertyName("destination")]
    public Place Destination { get; set; }

    /// <summary>Realtime time; null if cancelled.</summary>
    [JsonPropertyName("when")]
    public DateTimeOffset? When { get; set; }

    [JsonPropertyName("plannedWhen")]
    public DateTimeOffset? PlannedWhen { get; set; }

    [JsonPropertyName("prognosedWhen")]
    public DateTimeOffset? PrognosedWhen { get; set; }

    /// <summary>Seconds; null when unknown.</summary>
    [JsonPropertyName("delay")]
    public long? Delay { get; set; }

    /// <summary>Realtime platform; null if cancelled.</summary>
    [JsonPropertyName("platform")]
    public string Platform { get; set; }

    [JsonPropertyName("plannedPlatform")]
    public string PlannedPlatform { get; set; }

    [JsonPropertyName("prognosedPlatform")]
    public string PrognosedPlatform { get; set; }

    [JsonPropertyName("prognosisType")]
    public string? PrognosisType { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    [JsonPropertyName("cancelled")]
    public bool? Cancelled { get; set; }

    [JsonPropertyName("loadFactor")]
    public string LoadFactor { get; set; }

    [JsonPropertyName("previousStopovers")]
    public IReadOnlyList<Stopover> PreviousStopovers { get; set; }

    [JsonPropertyName("nextStopovers")]
    public IReadOnlyList<Stopover> NextStopovers { get; set; }

    /// <summary>Radar frames.</summary>
    [JsonPropertyName("frames")]
    public IReadOnlyList<Frame> Frames { get; set; }

    [JsonPropertyName("polyline")]
    public Polyline Polyline { get; set; }

    [JsonPropertyName("currentTripPosition")]
    public Location CurrentTripPosition { get; set; }

}

/// <summary>Radar frame: position of a vehicle between two places at offset t.</summary>
public class Frame
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("origin")]
    public Place Origin { get; set; }

    [JsonPropertyName("destination")]
    public Place Destination { get; set; }

    [JsonPropertyName("t")]
    public double? T { get; set; }

}

/// <summary>GeoJSON Point geometry.</summary>
public class GeometryPoint
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    /// <summary>[longitude, latitude].</summary>
    [JsonPropertyName("coordinates")]
    public IReadOnlyList<double> Coordinates { get; set; }

}

/// <summary>A computed set of directions to get from A to B at a specific time.</summary>
public class Journey
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>Pass to refresh_journey for realtime updates.</summary>
    [JsonPropertyName("refreshToken")]
    public string RefreshToken { get; set; }

    [JsonPropertyName("legs")]
    public IReadOnlyList<Leg> Legs { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    [JsonPropertyName("price")]
    public Price Price { get; set; }

    [JsonPropertyName("cycle")]
    public Cycle Cycle { get; set; }

    [JsonPropertyName("serviceDays")]
    public ServiceDays ServiceDays { get; set; }

    [JsonPropertyName("scheduledDays")]
    public ServiceDays ScheduledDays { get; set; }

}

/// <summary>One leg of a journey. Walking/transfer legs have walking=true and no line.</summary>
public class Leg
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("tripId")]
    public string TripId { get; set; }

    [JsonPropertyName("origin")]
    public Place Origin { get; set; }

    [JsonPropertyName("destination")]
    public Place Destination { get; set; }

    /// <summary>Absent for walking/transfer legs.</summary>
    [JsonPropertyName("line")]
    public Line Line { get; set; }

    [JsonPropertyName("direction")]
    public string Direction { get; set; }

    [JsonPropertyName("operator")]
    public Operator Operator { get; set; }

    [JsonPropertyName("departure")]
    public DateTimeOffset? Departure { get; set; }

    [JsonPropertyName("plannedDeparture")]
    public DateTimeOffset? PlannedDeparture { get; set; }

    [JsonPropertyName("prognosedDeparture")]
    public DateTimeOffset? PrognosedDeparture { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("departureDelay")]
    public long? DepartureDelay { get; set; }

    [JsonPropertyName("departurePlatform")]
    public string DeparturePlatform { get; set; }

    [JsonPropertyName("plannedDeparturePlatform")]
    public string PlannedDeparturePlatform { get; set; }

    [JsonPropertyName("prognosedDeparturePlatform")]
    public string PrognosedDeparturePlatform { get; set; }

    [JsonPropertyName("departurePrognosisType")]
    public string? DeparturePrognosisType { get; set; }

    [JsonPropertyName("arrival")]
    public DateTimeOffset? Arrival { get; set; }

    [JsonPropertyName("plannedArrival")]
    public DateTimeOffset? PlannedArrival { get; set; }

    [JsonPropertyName("prognosedArrival")]
    public DateTimeOffset? PrognosedArrival { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("arrivalDelay")]
    public long? ArrivalDelay { get; set; }

    [JsonPropertyName("arrivalPlatform")]
    public string ArrivalPlatform { get; set; }

    [JsonPropertyName("plannedArrivalPlatform")]
    public string PlannedArrivalPlatform { get; set; }

    [JsonPropertyName("prognosedArrivalPlatform")]
    public string PrognosedArrivalPlatform { get; set; }

    [JsonPropertyName("arrivalPrognosisType")]
    public string? ArrivalPrognosisType { get; set; }

    [JsonPropertyName("stopovers")]
    public IReadOnlyList<Stopover> Stopovers { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    [JsonPropertyName("walking")]
    public bool? Walking { get; set; }

    [JsonPropertyName("transfer")]
    public bool? Transfer { get; set; }

    /// <summary>Meters (walking/cycling/driving legs).</summary>
    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

    [JsonPropertyName("public")]
    public bool? Public { get; set; }

    /// <summary>Whether the transfer into this leg is guaranteed.</summary>
    [JsonPropertyName("reachable")]
    public bool? Reachable { get; set; }

    [JsonPropertyName("cancelled")]
    public bool? Cancelled { get; set; }

    [JsonPropertyName("loadFactor")]
    public string LoadFactor { get; set; }

    [JsonPropertyName("cycle")]
    public Cycle Cycle { get; set; }

    [JsonPropertyName("alternatives")]
    public IReadOnlyList<Departure> Alternatives { get; set; }

    [JsonPropertyName("polyline")]
    public Polyline Polyline { get; set; }

    [JsonPropertyName("price")]
    public Price Price { get; set; }

    [JsonPropertyName("schedule")]
    public long? Schedule { get; set; }

    [JsonPropertyName("currentLocation")]
    public Location CurrentLocation { get; set; }

    [JsonPropertyName("checkin")]
    public bool? Checkin { get; set; }

    [JsonPropertyName("serviceDays")]
    public ServiceDays ServiceDays { get; set; }

    /// <summary>hafas-client style; db-vendo uses serviceDays.</summary>
    [JsonPropertyName("scheduledDays")]
    public ServiceDays ScheduledDays { get; set; }

}

/// <summary>A public transport line.</summary>
public class Line
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("additionalName")]
    public string AdditionalName { get; set; }

    [JsonPropertyName("adminCode")]
    public string AdminCode { get; set; }

    [JsonPropertyName("fahrtNr")]
    public string FahrtNr { get; set; }

    /// <summary>Profile-specific product key (open string).</summary>
    [JsonPropertyName("product")]
    public string Product { get; set; }

    [JsonPropertyName("productName")]
    public string ProductName { get; set; }

    [JsonPropertyName("mode")]
    public string? Mode { get; set; }

    [JsonPropertyName("operator")]
    public Operator Operator { get; set; }

    [JsonPropertyName("express")]
    public bool? Express { get; set; }

    [JsonPropertyName("metro")]
    public bool? Metro { get; set; }

    [JsonPropertyName("night")]
    public bool? Night { get; set; }

    [JsonPropertyName("nr")]
    public long? Nr { get; set; }

    [JsonPropertyName("symbol")]
    public string Symbol { get; set; }

    [JsonPropertyName("public")]
    public bool? Public { get; set; }

    [JsonPropertyName("directions")]
    public IReadOnlyList<string> Directions { get; set; }

    /// <summary>Route ids.</summary>
    [JsonPropertyName("routes")]
    public IReadOnlyList<string> Routes { get; set; }

}

/// <summary>A point: POI, address or bare coordinate.</summary>
public class Location
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("poi")]
    public bool? Poi { get; set; }

    [JsonPropertyName("address")]
    public string Address { get; set; }

    [JsonPropertyName("latitude")]
    public double? Latitude { get; set; }

    [JsonPropertyName("longitude")]
    public double? Longitude { get; set; }

    [JsonPropertyName("altitude")]
    public double? Altitude { get; set; }

    /// <summary>Walking distance in meters (nearby results).</summary>
    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

}

/// <summary>A vehicle currently moving in the radar area.</summary>
public class Movement
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("direction")]
    public string Direction { get; set; }

    [JsonPropertyName("tripId")]
    public string TripId { get; set; }

    [JsonPropertyName("line")]
    public Line Line { get; set; }

    [JsonPropertyName("location")]
    public Location Location { get; set; }

    [JsonPropertyName("nextStopovers")]
    public IReadOnlyList<Stopover> NextStopovers { get; set; }

    [JsonPropertyName("frames")]
    public IReadOnlyList<Frame> Frames { get; set; }

    [JsonPropertyName("polyline")]
    public Polyline Polyline { get; set; }

}

/// <summary>Transit operator. Note: the upstream OpenAPI spec declares Trip.operator as number, but the wire format is an object; parsers must tolerate both.</summary>
public class Operator
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

}

/// <summary>GeoJSON FeatureCollection describing a trip/leg shape.</summary>
public class Polyline
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("features")]
    public IReadOnlyList<PolylineFeature> Features { get; set; }

}

/// <summary>GeoJSON Feature; properties describe the stop located at this position.</summary>
public class PolylineFeature
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("properties")]
    public LocationResult Properties { get; set; }

    [JsonPropertyName("geometry")]
    public GeometryPoint Geometry { get; set; }

}

/// <summary>Price information for a journey.</summary>
public class Price
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("amount")]
    public double? Amount { get; set; }

    [JsonPropertyName("currency")]
    public string Currency { get; set; }

    [JsonPropertyName("hint")]
    public string Hint { get; set; }

}

/// <summary>Reachability result: travel duration and reachable stations.</summary>
public class ReachableDuration
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("duration")]
    public long? Duration { get; set; }

    [JsonPropertyName("stations")]
    public IReadOnlyList<LocationResult> Stations { get; set; }

}

/// <summary>Hint, status or warning attached to journeys/legs/departures/trips/stops. Merged model of FPTF hint/status/warning.</summary>
public class Remark
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("type")]
    public string Kind { get; set; }

    [JsonPropertyName("code")]
    public string Code { get; set; }

    [JsonPropertyName("summary")]
    public string Summary { get; set; }

    [JsonPropertyName("text")]
    public string Text { get; set; }

    [JsonPropertyName("tripId")]
    public string TripId { get; set; }

    /// <summary>Warning id.</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("priority")]
    public long? Priority { get; set; }

    [JsonPropertyName("category")]
    public string Category { get; set; }

    [JsonPropertyName("products")]
    public Products Products { get; set; }

    [JsonPropertyName("company")]
    public string Company { get; set; }

    [JsonPropertyName("validFrom")]
    public DateTimeOffset? ValidFrom { get; set; }

    [JsonPropertyName("validUntil")]
    public DateTimeOffset? ValidUntil { get; set; }

    [JsonPropertyName("modified")]
    public DateTimeOffset? Modified { get; set; }

    [JsonPropertyName("affectedLines")]
    public IReadOnlyList<Line> AffectedLines { get; set; }

    [JsonPropertyName("fromStops")]
    public IReadOnlyList<LocationResult> FromStops { get; set; }

    [JsonPropertyName("toStops")]
    public IReadOnlyList<LocationResult> ToStops { get; set; }

}

/// <summary>A larger station area possibly containing multiple stops.</summary>
public class Station
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("station")]
    public Station Station { get; set; }

    [JsonPropertyName("location")]
    public Location Location { get; set; }

    [JsonPropertyName("products")]
    public Products Products { get; set; }

    [JsonPropertyName("lines")]
    public IReadOnlyList<Line> Lines { get; set; }

    [JsonPropertyName("isMeta")]
    public bool? IsMeta { get; set; }

    /// <summary>Region ids.</summary>
    [JsonPropertyName("regions")]
    public IReadOnlyList<string> Regions { get; set; }

    [JsonPropertyName("facilities")]
    public IReadOnlyDictionary<string, string> Facilities { get; set; }

    [JsonPropertyName("reisezentrumOpeningHours")]
    public OpeningHours OpeningHours { get; set; }

    /// <summary>Sub-stops.</summary>
    [JsonPropertyName("stops")]
    public IReadOnlyList<LocationResult> Stops { get; set; }

    [JsonPropertyName("entrances")]
    public IReadOnlyList<Location> Entrances { get; set; }

    [JsonPropertyName("transitAuthority")]
    public string TransitAuthority { get; set; }

    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

}

/// <summary>A single physical stop (platform, bus stop sign, ...).</summary>
public class Stop
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    /// <summary>Parent station.</summary>
    [JsonPropertyName("station")]
    public Station Station { get; set; }

    [JsonPropertyName("location")]
    public Location Location { get; set; }

    [JsonPropertyName("products")]
    public Products Products { get; set; }

    [JsonPropertyName("ids")]
    public Ids Ids { get; set; }

    [JsonPropertyName("lines")]
    public IReadOnlyList<Line> Lines { get; set; }

    [JsonPropertyName("entrances")]
    public IReadOnlyList<Location> Entrances { get; set; }

    [JsonPropertyName("isMeta")]
    public bool? IsMeta { get; set; }

    [JsonPropertyName("reisezentrumOpeningHours")]
    public OpeningHours OpeningHours { get; set; }

    /// <summary>Open value set: low/medium/high/...</summary>
    [JsonPropertyName("loadFactor")]
    public string LoadFactor { get; set; }

    [JsonPropertyName("transitAuthority")]
    public string TransitAuthority { get; set; }

    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

}

/// <summary>A vehicle stopping at a stop at specific times.</summary>
public class Stopover
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("stop")]
    public StopOrStation Stop { get; set; }

    /// <summary>Null/absent on the first stopover.</summary>
    [JsonPropertyName("arrival")]
    public DateTimeOffset? Arrival { get; set; }

    [JsonPropertyName("plannedArrival")]
    public DateTimeOffset? PlannedArrival { get; set; }

    [JsonPropertyName("prognosedArrival")]
    public DateTimeOffset? PrognosedArrival { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("arrivalDelay")]
    public long? ArrivalDelay { get; set; }

    [JsonPropertyName("arrivalPlatform")]
    public string ArrivalPlatform { get; set; }

    [JsonPropertyName("plannedArrivalPlatform")]
    public string PlannedArrivalPlatform { get; set; }

    [JsonPropertyName("prognosedArrivalPlatform")]
    public string PrognosedArrivalPlatform { get; set; }

    [JsonPropertyName("arrivalPrognosisType")]
    public string? ArrivalPrognosisType { get; set; }

    /// <summary>Null/absent on the last stopover.</summary>
    [JsonPropertyName("departure")]
    public DateTimeOffset? Departure { get; set; }

    [JsonPropertyName("plannedDeparture")]
    public DateTimeOffset? PlannedDeparture { get; set; }

    [JsonPropertyName("prognosedDeparture")]
    public DateTimeOffset? PrognosedDeparture { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("departureDelay")]
    public long? DepartureDelay { get; set; }

    [JsonPropertyName("departurePlatform")]
    public string DeparturePlatform { get; set; }

    [JsonPropertyName("plannedDeparturePlatform")]
    public string PlannedDeparturePlatform { get; set; }

    [JsonPropertyName("prognosedDeparturePlatform")]
    public string PrognosedDeparturePlatform { get; set; }

    [JsonPropertyName("departurePrognosisType")]
    public string? DeparturePrognosisType { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    /// <summary>Vehicle passes without stopping.</summary>
    [JsonPropertyName("passBy")]
    public bool? PassBy { get; set; }

    [JsonPropertyName("cancelled")]
    public bool? Cancelled { get; set; }

    /// <summary>Extra, unscheduled stop.</summary>
    [JsonPropertyName("additional")]
    public bool? Additional { get; set; }

}

/// <summary>A specific vehicle stopping at a set of stops at specific times.</summary>
public class Trip
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("origin")]
    public Place Origin { get; set; }

    [JsonPropertyName("destination")]
    public Place Destination { get; set; }

    [JsonPropertyName("line")]
    public Line Line { get; set; }

    [JsonPropertyName("direction")]
    public string Direction { get; set; }

    [JsonPropertyName("operator")]
    public Operator Operator { get; set; }

    [JsonPropertyName("departure")]
    public DateTimeOffset? Departure { get; set; }

    [JsonPropertyName("plannedDeparture")]
    public DateTimeOffset? PlannedDeparture { get; set; }

    [JsonPropertyName("prognosedDeparture")]
    public DateTimeOffset? PrognosedDeparture { get; set; }

    [JsonPropertyName("departureDelay")]
    public long? DepartureDelay { get; set; }

    [JsonPropertyName("departurePlatform")]
    public string DeparturePlatform { get; set; }

    [JsonPropertyName("plannedDeparturePlatform")]
    public string PlannedDeparturePlatform { get; set; }

    [JsonPropertyName("prognosedDeparturePlatform")]
    public string PrognosedDeparturePlatform { get; set; }

    [JsonPropertyName("departurePrognosisType")]
    public string? DeparturePrognosisType { get; set; }

    [JsonPropertyName("arrival")]
    public DateTimeOffset? Arrival { get; set; }

    [JsonPropertyName("plannedArrival")]
    public DateTimeOffset? PlannedArrival { get; set; }

    [JsonPropertyName("prognosedArrival")]
    public DateTimeOffset? PrognosedArrival { get; set; }

    [JsonPropertyName("arrivalDelay")]
    public long? ArrivalDelay { get; set; }

    [JsonPropertyName("arrivalPlatform")]
    public string ArrivalPlatform { get; set; }

    [JsonPropertyName("plannedArrivalPlatform")]
    public string PlannedArrivalPlatform { get; set; }

    [JsonPropertyName("prognosedArrivalPlatform")]
    public string PrognosedArrivalPlatform { get; set; }

    [JsonPropertyName("arrivalPrognosisType")]
    public string? ArrivalPrognosisType { get; set; }

    [JsonPropertyName("stopovers")]
    public IReadOnlyList<Stopover> Stopovers { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    [JsonPropertyName("walking")]
    public bool? Walking { get; set; }

    [JsonPropertyName("transfer")]
    public bool? Transfer { get; set; }

    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

    [JsonPropertyName("public")]
    public bool? Public { get; set; }

    [JsonPropertyName("cancelled")]
    public bool? Cancelled { get; set; }

    [JsonPropertyName("loadFactor")]
    public string LoadFactor { get; set; }

    [JsonPropertyName("cycle")]
    public Cycle Cycle { get; set; }

    [JsonPropertyName("alternatives")]
    public IReadOnlyList<Departure> Alternatives { get; set; }

    [JsonPropertyName("polyline")]
    public Polyline Polyline { get; set; }

    [JsonPropertyName("price")]
    public Price Price { get; set; }

    [JsonPropertyName("schedule")]
    public long? Schedule { get; set; }

    [JsonPropertyName("currentLocation")]
    public Location CurrentLocation { get; set; }

    [JsonPropertyName("checkin")]
    public bool? Checkin { get; set; }

    [JsonPropertyName("serviceDays")]
    public ServiceDays ServiceDays { get; set; }

    [JsonPropertyName("scheduledDays")]
    public ServiceDays ScheduledDays { get; set; }

}

/// <summary>Response of GET /stops/{id}/arrivals.</summary>
public class ArrivalsResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("arrivals")]
    public IReadOnlyList<Departure> Arrivals { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /stops/{id}/departures.</summary>
public class DeparturesResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("departures")]
    public IReadOnlyList<Departure> Departures { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /journeys/{ref}.</summary>
public class JourneyResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("journey")]
    public Journey Journey { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /journeys.</summary>
public class JourneysResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("journeys")]
    public IReadOnlyList<Journey> Journeys { get; set; }

    [JsonPropertyName("earlierRef")]
    public string EarlierRef { get; set; }

    [JsonPropertyName("laterRef")]
    public string LaterRef { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /radar.</summary>
public class RadarResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("movements")]
    public IReadOnlyList<Movement> Movements { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /stops/reachable-from.</summary>
public class ReachableFromResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("reachable")]
    public IReadOnlyList<ReachableDuration> Reachable { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /trips/{id}.</summary>
public class TripResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("trip")]
    public Trip Trip { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /trips (trips by name).</summary>
public class TripsResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("trips")]
    public IReadOnlyList<Trip> Trips { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

