// <auto-generated>
// Code generated by transport-rest-gen. DO NOT EDIT.
// </auto-generated>

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Ids = IReadOnlyDictionary<string, string>;
using OpeningHours = IReadOnlyDictionary<string, string>;
using Products = IReadOnlyDictionary<string, bool>;
using ServiceDays = IReadOnlyDictionary<string, bool>;

namespace TransportRest.Models;

/// <summary>Accessibility</summary>
public enum Accessibility : string
{
    [JsonStringEnumMemberName("partial")]
    partial,
    [JsonStringEnumMemberName("complete")]
    complete,
}

/// <summary>AgeGroup</summary>
public enum AgeGroup : string
{
    [JsonStringEnumMemberName("B")]
    B,
    [JsonStringEnumMemberName("E")]
    E,
    [JsonStringEnumMemberName("K")]
    K,
    [JsonStringEnumMemberName("S")]
    S,
    [JsonStringEnumMemberName("Y")]
    Y,
}

/// <summary>db-vendo backend profile selector of the DB instance.</summary>
public enum DbProfile : string
{
    [JsonStringEnumMemberName("dbnav")]
    dbnav,
    [JsonStringEnumMemberName("db")]
    db,
    [JsonStringEnumMemberName("dbweb")]
    dbweb,
}

/// <summary>LoyaltyCard</summary>
public enum LoyaltyCard : string
{
    [JsonStringEnumMemberName("bahncard-1st-25")]
    bahncard_1st_25,
    [JsonStringEnumMemberName("bahncard-2nd-25")]
    bahncard_2nd_25,
    [JsonStringEnumMemberName("bahncard-1st-50")]
    bahncard_1st_50,
    [JsonStringEnumMemberName("bahncard-2nd-50")]
    bahncard_2nd_50,
    [JsonStringEnumMemberName("bahncard-1st-100")]
    bahncard_1st_100,
    [JsonStringEnumMemberName("bahncard-2nd-100")]
    bahncard_2nd_100,
    [JsonStringEnumMemberName("vorteilscard")]
    vorteilscard,
    [JsonStringEnumMemberName("halbtaxabo")]
    halbtaxabo,
    [JsonStringEnumMemberName("generalabonnement-1st")]
    generalabonnement_1st,
    [JsonStringEnumMemberName("generalabonnement-2nd")]
    generalabonnement_2nd,
    [JsonStringEnumMemberName("nl-40")]
    nl_40,
    [JsonStringEnumMemberName("at-klimaticket")]
    at_klimaticket,
}

/// <summary>Means of transport mode (FPTF). Open enum: unknown wire values map to the fallback variant.</summary>
public enum Mode : string
{
    [JsonStringEnumMemberName("aircraft")]
    aircraft,
    [JsonStringEnumMemberName("bicycle")]
    bicycle,
    [JsonStringEnumMemberName("bus")]
    bus,
    [JsonStringEnumMemberName("car")]
    car,
    [JsonStringEnumMemberName("gondola")]
    gondola,
    [JsonStringEnumMemberName("taxi")]
    taxi,
    [JsonStringEnumMemberName("train")]
    train,
    [JsonStringEnumMemberName("walking")]
    walking,
    [JsonStringEnumMemberName("watercraft")]
    watercraft,
}

/// <summary>Reliability class of a prognosis.</summary>
public enum PrognosisType : string
{
    [JsonStringEnumMemberName("calculated")]
    calculated,
    [JsonStringEnumMemberName("prognosed")]
    prognosed,
}

/// <summary>Discriminator of remark objects; FPTF hint/status/warning are merged into one model.</summary>
public enum RemarkKind : string
{
    [JsonStringEnumMemberName("hint")]
    hint,
    [JsonStringEnumMemberName("status")]
    status,
    [JsonStringEnumMemberName("warning")]
    warning,
    [JsonStringEnumMemberName("foreign-id")]
    foreign_id,
    [JsonStringEnumMemberName("local-fare-zone")]
    local_fare_zone,
    [JsonStringEnumMemberName("stop-dhid")]
    stop_dhid,
    [JsonStringEnumMemberName("stop-website")]
    stop_website,
    [JsonStringEnumMemberName("transit-authority")]
    transit_authority,
}

/// <summary>REALTIME is the default and excludes cancelled journeys; HYBRID includes them and fully supports pagination.</summary>
public enum RoutingMode : string
{
    [JsonStringEnumMemberName("FULL")]
    FULL,
    [JsonStringEnumMemberName("HYBRID")]
    HYBRID,
    [JsonStringEnumMemberName("INFOS")]
    INFOS,
    [JsonStringEnumMemberName("OFF")]
    OFF,
    [JsonStringEnumMemberName("REALTIME")]
    REALTIME,
    [JsonStringEnumMemberName("SERVER_DEFAULT")]
    SERVER_DEFAULT,
}

/// <summary>WalkingSpeed</summary>
public enum WalkingSpeed : string
{
    [JsonStringEnumMemberName("slow")]
    slow,
    [JsonStringEnumMemberName("normal")]
    normal,
    [JsonStringEnumMemberName("fast")]
    fast,
}

/// <summary>LocationResult - tagged union (stop/station/location or unknown type); kept as raw JSON.</summary>
public sealed class LocationResult
{
    public LocationResult(JsonElement raw) { Raw = raw; }

    public JsonElement Raw { get; }
}

/// <summary>Place - tagged union (stop/station/location or unknown type); kept as raw JSON.</summary>
public sealed class Place
{
    public Place(JsonElement raw) { Raw = raw; }

    public JsonElement Raw { get; }
}

/// <summary>StopOrStation - tagged union (stop/station/location or unknown type); kept as raw JSON.</summary>
public sealed class StopOrStation
{
    public StopOrStation(JsonElement raw) { Raw = raw; }

    public JsonElement Raw { get; }
}

/// <summary>Cycle times of a line/trip in minutes.</summary>
public class Cycle
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("min")]
    public long? Min { get; set; }

    [JsonPropertyName("max")]
    public long? Max { get; set; }

    [JsonPropertyName("nr")]
    public long? Nr { get; set; }

}

/// <summary>A departure or arrival board entry (OpenAPI schema name: Alternative).</summary>
public class Departure
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("tripId")]
    public string TripId { get; set; }

    [JsonPropertyName("stop")]
    public StopOrStation Stop { get; set; }

    /// <summary>Current vehicle position (radar).</summary>
    [JsonPropertyName("location")]
    public Location Location { get; set; }

    [JsonPropertyName("line")]
    public Line Line { get; set; }

    [JsonPropertyName("direction")]
    public string Direction { get; set; }

    /// <summary>Origin of the vehicle (arrivals boards).</summary>
    [JsonPropertyName("provenance")]
    public string Provenance { get; set; }

    [JsonPropertyName("origin")]
    public Place Origin { get; set; }

    [JsonPropertyName("destination")]
    public Place Destination { get; set; }

    /// <summary>Realtime time; null if cancelled.</summary>
    [JsonPropertyName("when")]
    public DateTimeOffset? When { get; set; }

    [JsonPropertyName("plannedWhen")]
    public DateTimeOffset? PlannedWhen { get; set; }

    [JsonPropertyName("prognosedWhen")]
    public DateTimeOffset? PrognosedWhen { get; set; }

    /// <summary>Seconds; null when unknown.</summary>
    [JsonPropertyName("delay")]
    public long? Delay { get; set; }

    /// <summary>Realtime platform; null if cancelled.</summary>
    [JsonPropertyName("platform")]
    public string Platform { get; set; }

    [JsonPropertyName("plannedPlatform")]
    public string PlannedPlatform { get; set; }

    [JsonPropertyName("prognosedPlatform")]
    public string PrognosedPlatform { get; set; }

    [JsonPropertyName("prognosisType")]
    public PrognosisType PrognosisType { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    [JsonPropertyName("cancelled")]
    public bool? Cancelled { get; set; }

    [JsonPropertyName("loadFactor")]
    public string LoadFactor { get; set; }

    [JsonPropertyName("previousStopovers")]
    public IReadOnlyList<Stopover> PreviousStopovers { get; set; }

    [JsonPropertyName("nextStopovers")]
    public IReadOnlyList<Stopover> NextStopovers { get; set; }

    /// <summary>Radar frames.</summary>
    [JsonPropertyName("frames")]
    public IReadOnlyList<Frame> Frames { get; set; }

    [JsonPropertyName("polyline")]
    public Polyline Polyline { get; set; }

    [JsonPropertyName("currentTripPosition")]
    public Location CurrentTripPosition { get; set; }

}

/// <summary>Radar frame: position of a vehicle between two places at offset t.</summary>
public class Frame
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("origin")]
    public Place Origin { get; set; }

    [JsonPropertyName("destination")]
    public Place Destination { get; set; }

    [JsonPropertyName("t")]
    public double? T { get; set; }

}

/// <summary>GeoJSON Point geometry.</summary>
public class GeometryPoint
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    /// <summary>[longitude, latitude].</summary>
    [JsonPropertyName("coordinates")]
    public IReadOnlyList<double> Coordinates { get; set; }

}

/// <summary>A computed set of directions to get from A to B at a specific time.</summary>
public class Journey
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    /// <summary>Pass to refresh_journey for realtime updates.</summary>
    [JsonPropertyName("refreshToken")]
    public string RefreshToken { get; set; }

    [JsonPropertyName("legs")]
    public IReadOnlyList<Leg> Legs { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    [JsonPropertyName("price")]
    public Price Price { get; set; }

    [JsonPropertyName("cycle")]
    public Cycle Cycle { get; set; }

    [JsonPropertyName("serviceDays")]
    public ServiceDays ServiceDays { get; set; }

    [JsonPropertyName("scheduledDays")]
    public ServiceDays ScheduledDays { get; set; }

}

/// <summary>One leg of a journey. Walking/transfer legs have walking=true and no line.</summary>
public class Leg
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("tripId")]
    public string TripId { get; set; }

    [JsonPropertyName("origin")]
    public Place Origin { get; set; }

    [JsonPropertyName("destination")]
    public Place Destination { get; set; }

    /// <summary>Absent for walking/transfer legs.</summary>
    [JsonPropertyName("line")]
    public Line Line { get; set; }

    [JsonPropertyName("direction")]
    public string Direction { get; set; }

    [JsonPropertyName("operator")]
    public Operator Operator { get; set; }

    [JsonPropertyName("departure")]
    public DateTimeOffset? Departure { get; set; }

    [JsonPropertyName("plannedDeparture")]
    public DateTimeOffset? PlannedDeparture { get; set; }

    [JsonPropertyName("prognosedDeparture")]
    public DateTimeOffset? PrognosedDeparture { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("departureDelay")]
    public long? DepartureDelay { get; set; }

    [JsonPropertyName("departurePlatform")]
    public string DeparturePlatform { get; set; }

    [JsonPropertyName("plannedDeparturePlatform")]
    public string PlannedDeparturePlatform { get; set; }

    [JsonPropertyName("prognosedDeparturePlatform")]
    public string PrognosedDeparturePlatform { get; set; }

    [JsonPropertyName("departurePrognosisType")]
    public PrognosisType DeparturePrognosisType { get; set; }

    [JsonPropertyName("arrival")]
    public DateTimeOffset? Arrival { get; set; }

    [JsonPropertyName("plannedArrival")]
    public DateTimeOffset? PlannedArrival { get; set; }

    [JsonPropertyName("prognosedArrival")]
    public DateTimeOffset? PrognosedArrival { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("arrivalDelay")]
    public long? ArrivalDelay { get; set; }

    [JsonPropertyName("arrivalPlatform")]
    public string ArrivalPlatform { get; set; }

    [JsonPropertyName("plannedArrivalPlatform")]
    public string PlannedArrivalPlatform { get; set; }

    [JsonPropertyName("prognosedArrivalPlatform")]
    public string PrognosedArrivalPlatform { get; set; }

    [JsonPropertyName("arrivalPrognosisType")]
    public PrognosisType ArrivalPrognosisType { get; set; }

    [JsonPropertyName("stopovers")]
    public IReadOnlyList<Stopover> Stopovers { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    [JsonPropertyName("walking")]
    public bool? Walking { get; set; }

    [JsonPropertyName("transfer")]
    public bool? Transfer { get; set; }

    /// <summary>Meters (walking/cycling/driving legs).</summary>
    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

    [JsonPropertyName("public")]
    public bool? Public { get; set; }

    /// <summary>Whether the transfer into this leg is guaranteed.</summary>
    [JsonPropertyName("reachable")]
    public bool? Reachable { get; set; }

    [JsonPropertyName("cancelled")]
    public bool? Cancelled { get; set; }

    [JsonPropertyName("loadFactor")]
    public string LoadFactor { get; set; }

    [JsonPropertyName("cycle")]
    public Cycle Cycle { get; set; }

    [JsonPropertyName("alternatives")]
    public IReadOnlyList<Departure> Alternatives { get; set; }

    [JsonPropertyName("polyline")]
    public Polyline Polyline { get; set; }

    [JsonPropertyName("price")]
    public Price Price { get; set; }

    [JsonPropertyName("schedule")]
    public long? Schedule { get; set; }

    [JsonPropertyName("currentLocation")]
    public Location CurrentLocation { get; set; }

    [JsonPropertyName("checkin")]
    public bool? Checkin { get; set; }

    [JsonPropertyName("serviceDays")]
    public ServiceDays ServiceDays { get; set; }

    /// <summary>hafas-client style; db-vendo uses serviceDays.</summary>
    [JsonPropertyName("scheduledDays")]
    public ServiceDays ScheduledDays { get; set; }

}

/// <summary>A public transport line.</summary>
public class Line
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("additionalName")]
    public string AdditionalName { get; set; }

    [JsonPropertyName("adminCode")]
    public string AdminCode { get; set; }

    [JsonPropertyName("fahrtNr")]
    public string FahrtNr { get; set; }

    /// <summary>Profile-specific product key (open string).</summary>
    [JsonPropertyName("product")]
    public string Product { get; set; }

    [JsonPropertyName("productName")]
    public string ProductName { get; set; }

    [JsonPropertyName("mode")]
    public Mode Mode { get; set; }

    [JsonPropertyName("operator")]
    public Operator Operator { get; set; }

    [JsonPropertyName("express")]
    public bool? Express { get; set; }

    [JsonPropertyName("metro")]
    public bool? Metro { get; set; }

    [JsonPropertyName("night")]
    public bool? Night { get; set; }

    [JsonPropertyName("nr")]
    public long? Nr { get; set; }

    [JsonPropertyName("symbol")]
    public string Symbol { get; set; }

    [JsonPropertyName("public")]
    public bool? Public { get; set; }

    [JsonPropertyName("directions")]
    public IReadOnlyList<string> Directions { get; set; }

    /// <summary>Route ids.</summary>
    [JsonPropertyName("routes")]
    public IReadOnlyList<string> Routes { get; set; }

}

/// <summary>A point: POI, address or bare coordinate.</summary>
public class Location
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("poi")]
    public bool? Poi { get; set; }

    [JsonPropertyName("address")]
    public string Address { get; set; }

    [JsonPropertyName("latitude")]
    public double? Latitude { get; set; }

    [JsonPropertyName("longitude")]
    public double? Longitude { get; set; }

    [JsonPropertyName("altitude")]
    public double? Altitude { get; set; }

    /// <summary>Walking distance in meters (nearby results).</summary>
    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

}

/// <summary>A vehicle currently moving in the radar area.</summary>
public class Movement
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("direction")]
    public string Direction { get; set; }

    [JsonPropertyName("tripId")]
    public string TripId { get; set; }

    [JsonPropertyName("line")]
    public Line Line { get; set; }

    [JsonPropertyName("location")]
    public Location Location { get; set; }

    [JsonPropertyName("nextStopovers")]
    public IReadOnlyList<Stopover> NextStopovers { get; set; }

    [JsonPropertyName("frames")]
    public IReadOnlyList<Frame> Frames { get; set; }

    [JsonPropertyName("polyline")]
    public Polyline Polyline { get; set; }

}

/// <summary>Transit operator. Note: the upstream OpenAPI spec declares Trip.operator as number, but the wire format is an object; parsers must tolerate both.</summary>
public class Operator
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

}

/// <summary>GeoJSON FeatureCollection describing a trip/leg shape.</summary>
public class Polyline
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("features")]
    public IReadOnlyList<PolylineFeature> Features { get; set; }

}

/// <summary>GeoJSON Feature; properties describe the stop located at this position.</summary>
public class PolylineFeature
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("properties")]
    public LocationResult Properties { get; set; }

    [JsonPropertyName("geometry")]
    public GeometryPoint Geometry { get; set; }

}

/// <summary>Price information for a journey.</summary>
public class Price
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("amount")]
    public double? Amount { get; set; }

    [JsonPropertyName("currency")]
    public string Currency { get; set; }

    [JsonPropertyName("hint")]
    public string Hint { get; set; }

}

/// <summary>Reachability result: travel duration and reachable stations.</summary>
public class ReachableDuration
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("duration")]
    public long? Duration { get; set; }

    [JsonPropertyName("stations")]
    public IReadOnlyList<LocationResult> Stations { get; set; }

}

/// <summary>Hint, status or warning attached to journeys/legs/departures/trips/stops. Merged model of FPTF hint/status/warning.</summary>
public class Remark
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("type")]
    public RemarkKind Kind { get; set; }

    [JsonPropertyName("code")]
    public string Code { get; set; }

    [JsonPropertyName("summary")]
    public string Summary { get; set; }

    [JsonPropertyName("text")]
    public string Text { get; set; }

    [JsonPropertyName("tripId")]
    public string TripId { get; set; }

    /// <summary>Warning id.</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("priority")]
    public long? Priority { get; set; }

    [JsonPropertyName("category")]
    public string Category { get; set; }

    [JsonPropertyName("products")]
    public Products Products { get; set; }

    [JsonPropertyName("company")]
    public string Company { get; set; }

    [JsonPropertyName("validFrom")]
    public DateTimeOffset? ValidFrom { get; set; }

    [JsonPropertyName("validUntil")]
    public DateTimeOffset? ValidUntil { get; set; }

    [JsonPropertyName("modified")]
    public DateTimeOffset? Modified { get; set; }

    [JsonPropertyName("affectedLines")]
    public IReadOnlyList<Line> AffectedLines { get; set; }

    [JsonPropertyName("fromStops")]
    public IReadOnlyList<LocationResult> FromStops { get; set; }

    [JsonPropertyName("toStops")]
    public IReadOnlyList<LocationResult> ToStops { get; set; }

}

/// <summary>A larger station area possibly containing multiple stops.</summary>
public class Station
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("station")]
    public Station Station { get; set; }

    [JsonPropertyName("location")]
    public Location Location { get; set; }

    [JsonPropertyName("products")]
    public Products Products { get; set; }

    [JsonPropertyName("lines")]
    public IReadOnlyList<Line> Lines { get; set; }

    [JsonPropertyName("isMeta")]
    public bool? IsMeta { get; set; }

    /// <summary>Region ids.</summary>
    [JsonPropertyName("regions")]
    public IReadOnlyList<string> Regions { get; set; }

    [JsonPropertyName("facilities")]
    public IReadOnlyDictionary<string, string> Facilities { get; set; }

    [JsonPropertyName("reisezentrumOpeningHours")]
    public OpeningHours OpeningHours { get; set; }

    /// <summary>Sub-stops.</summary>
    [JsonPropertyName("stops")]
    public IReadOnlyList<LocationResult> Stops { get; set; }

    [JsonPropertyName("entrances")]
    public IReadOnlyList<Location> Entrances { get; set; }

    [JsonPropertyName("transitAuthority")]
    public string TransitAuthority { get; set; }

    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

}

/// <summary>A single physical stop (platform, bus stop sign, ...).</summary>
public class Stop
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    /// <summary>Parent station.</summary>
    [JsonPropertyName("station")]
    public Station Station { get; set; }

    [JsonPropertyName("location")]
    public Location Location { get; set; }

    [JsonPropertyName("products")]
    public Products Products { get; set; }

    [JsonPropertyName("ids")]
    public Ids Ids { get; set; }

    [JsonPropertyName("lines")]
    public IReadOnlyList<Line> Lines { get; set; }

    [JsonPropertyName("entrances")]
    public IReadOnlyList<Location> Entrances { get; set; }

    [JsonPropertyName("isMeta")]
    public bool? IsMeta { get; set; }

    [JsonPropertyName("reisezentrumOpeningHours")]
    public OpeningHours OpeningHours { get; set; }

    /// <summary>Open value set: low/medium/high/...</summary>
    [JsonPropertyName("loadFactor")]
    public string LoadFactor { get; set; }

    [JsonPropertyName("transitAuthority")]
    public string TransitAuthority { get; set; }

    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

}

/// <summary>A vehicle stopping at a stop at specific times.</summary>
public class Stopover
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("stop")]
    public StopOrStation Stop { get; set; }

    /// <summary>Null/absent on the first stopover.</summary>
    [JsonPropertyName("arrival")]
    public DateTimeOffset? Arrival { get; set; }

    [JsonPropertyName("plannedArrival")]
    public DateTimeOffset? PlannedArrival { get; set; }

    [JsonPropertyName("prognosedArrival")]
    public DateTimeOffset? PrognosedArrival { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("arrivalDelay")]
    public long? ArrivalDelay { get; set; }

    [JsonPropertyName("arrivalPlatform")]
    public string ArrivalPlatform { get; set; }

    [JsonPropertyName("plannedArrivalPlatform")]
    public string PlannedArrivalPlatform { get; set; }

    [JsonPropertyName("prognosedArrivalPlatform")]
    public string PrognosedArrivalPlatform { get; set; }

    [JsonPropertyName("arrivalPrognosisType")]
    public PrognosisType ArrivalPrognosisType { get; set; }

    /// <summary>Null/absent on the last stopover.</summary>
    [JsonPropertyName("departure")]
    public DateTimeOffset? Departure { get; set; }

    [JsonPropertyName("plannedDeparture")]
    public DateTimeOffset? PlannedDeparture { get; set; }

    [JsonPropertyName("prognosedDeparture")]
    public DateTimeOffset? PrognosedDeparture { get; set; }

    /// <summary>Seconds.</summary>
    [JsonPropertyName("departureDelay")]
    public long? DepartureDelay { get; set; }

    [JsonPropertyName("departurePlatform")]
    public string DeparturePlatform { get; set; }

    [JsonPropertyName("plannedDeparturePlatform")]
    public string PlannedDeparturePlatform { get; set; }

    [JsonPropertyName("prognosedDeparturePlatform")]
    public string PrognosedDeparturePlatform { get; set; }

    [JsonPropertyName("departurePrognosisType")]
    public PrognosisType DeparturePrognosisType { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    /// <summary>Vehicle passes without stopping.</summary>
    [JsonPropertyName("passBy")]
    public bool? PassBy { get; set; }

    [JsonPropertyName("cancelled")]
    public bool? Cancelled { get; set; }

    /// <summary>Extra, unscheduled stop.</summary>
    [JsonPropertyName("additional")]
    public bool? Additional { get; set; }

}

/// <summary>A specific vehicle stopping at a set of stops at specific times.</summary>
public class Trip
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("origin")]
    public Place Origin { get; set; }

    [JsonPropertyName("destination")]
    public Place Destination { get; set; }

    [JsonPropertyName("line")]
    public Line Line { get; set; }

    [JsonPropertyName("direction")]
    public string Direction { get; set; }

    [JsonPropertyName("operator")]
    public Operator Operator { get; set; }

    [JsonPropertyName("departure")]
    public DateTimeOffset? Departure { get; set; }

    [JsonPropertyName("plannedDeparture")]
    public DateTimeOffset? PlannedDeparture { get; set; }

    [JsonPropertyName("prognosedDeparture")]
    public DateTimeOffset? PrognosedDeparture { get; set; }

    [JsonPropertyName("departureDelay")]
    public long? DepartureDelay { get; set; }

    [JsonPropertyName("departurePlatform")]
    public string DeparturePlatform { get; set; }

    [JsonPropertyName("plannedDeparturePlatform")]
    public string PlannedDeparturePlatform { get; set; }

    [JsonPropertyName("prognosedDeparturePlatform")]
    public string PrognosedDeparturePlatform { get; set; }

    [JsonPropertyName("departurePrognosisType")]
    public PrognosisType DeparturePrognosisType { get; set; }

    [JsonPropertyName("arrival")]
    public DateTimeOffset? Arrival { get; set; }

    [JsonPropertyName("plannedArrival")]
    public DateTimeOffset? PlannedArrival { get; set; }

    [JsonPropertyName("prognosedArrival")]
    public DateTimeOffset? PrognosedArrival { get; set; }

    [JsonPropertyName("arrivalDelay")]
    public long? ArrivalDelay { get; set; }

    [JsonPropertyName("arrivalPlatform")]
    public string ArrivalPlatform { get; set; }

    [JsonPropertyName("plannedArrivalPlatform")]
    public string PlannedArrivalPlatform { get; set; }

    [JsonPropertyName("prognosedArrivalPlatform")]
    public string PrognosedArrivalPlatform { get; set; }

    [JsonPropertyName("arrivalPrognosisType")]
    public PrognosisType ArrivalPrognosisType { get; set; }

    [JsonPropertyName("stopovers")]
    public IReadOnlyList<Stopover> Stopovers { get; set; }

    [JsonPropertyName("remarks")]
    public IReadOnlyList<Remark> Remarks { get; set; }

    [JsonPropertyName("walking")]
    public bool? Walking { get; set; }

    [JsonPropertyName("transfer")]
    public bool? Transfer { get; set; }

    [JsonPropertyName("distance")]
    public double? Distance { get; set; }

    [JsonPropertyName("public")]
    public bool? Public { get; set; }

    [JsonPropertyName("cancelled")]
    public bool? Cancelled { get; set; }

    [JsonPropertyName("loadFactor")]
    public string LoadFactor { get; set; }

    [JsonPropertyName("cycle")]
    public Cycle Cycle { get; set; }

    [JsonPropertyName("alternatives")]
    public IReadOnlyList<Departure> Alternatives { get; set; }

    [JsonPropertyName("polyline")]
    public Polyline Polyline { get; set; }

    [JsonPropertyName("price")]
    public Price Price { get; set; }

    [JsonPropertyName("schedule")]
    public long? Schedule { get; set; }

    [JsonPropertyName("currentLocation")]
    public Location CurrentLocation { get; set; }

    [JsonPropertyName("checkin")]
    public bool? Checkin { get; set; }

    [JsonPropertyName("serviceDays")]
    public ServiceDays ServiceDays { get; set; }

    [JsonPropertyName("scheduledDays")]
    public ServiceDays ScheduledDays { get; set; }

}

/// <summary>Response of GET /stops/{id}/arrivals.</summary>
public class ArrivalsResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("arrivals")]
    public IReadOnlyList<Departure> Arrivals { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /stops/{id}/departures.</summary>
public class DeparturesResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("departures")]
    public IReadOnlyList<Departure> Departures { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /journeys/{ref}.</summary>
public class JourneyResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("journey")]
    public Journey Journey { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /journeys.</summary>
public class JourneysResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("journeys")]
    public IReadOnlyList<Journey> Journeys { get; set; }

    [JsonPropertyName("earlierRef")]
    public string EarlierRef { get; set; }

    [JsonPropertyName("laterRef")]
    public string LaterRef { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /radar.</summary>
public class RadarResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("movements")]
    public IReadOnlyList<Movement> Movements { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /stops/reachable-from.</summary>
public class ReachableFromResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("reachable")]
    public IReadOnlyList<ReachableDuration> Reachable { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /trips/{id}.</summary>
public class TripResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("trip")]
    public Trip Trip { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

/// <summary>Response of GET /trips (trips by name).</summary>
public class TripsResponse
{
    /// <summary>Unknown future JSON fields, preserved verbatim.</summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? ExtensionData { get; set; }

    [JsonPropertyName("trips")]
    public IReadOnlyList<Trip> Trips { get; set; }

    [JsonPropertyName("realtimeDataUpdatedAt")]
    public long? RealtimeDataUpdatedAt { get; set; }

}

