"""Generated by transport-rest-gen. DO NOT EDIT.

Source of truth: schema/*.json (see docs/API_ANALYSIS.md).
All models ignore unknown JSON fields and tolerate null values.
"""

from __future__ import annotations

import dataclasses
import datetime as _dt
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Shared aliases (see schema/types.json for known keys/values)
# ---------------------------------------------------------------------------

Products = dict[str, bool]
Ids = dict[str, str]
ServiceDays = dict[str, bool]
OpeningHours = dict[str, str]


def _parse_dt(value: Any) -> Any:
    try:
        return _dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except (TypeError, ValueError, AttributeError):
        return value

# ---------------------------------------------------------------------------
# Tagged unions (dispatch on the wire `type` field; unknown -> raw dict)
# ---------------------------------------------------------------------------

Accessibility = str  # open enum: Accessibility
AgeGroup = str  # open enum: AgeGroup
DbProfile = str  # open enum: db-vendo backend profile selector of the DB instance.
LoyaltyCard = str  # open enum: LoyaltyCard
Mode = str  # open enum: Means of transport mode (FPTF). Open enum: unknown wire values map to the fallback variant.
PrognosisType = str  # open enum: Reliability class of a prognosis.
RemarkKind = str  # open enum: Discriminator of remark objects; FPTF hint/status/warning are merged into one model.
RoutingMode = str  # open enum: REALTIME is the default and excludes cancelled journeys; HYBRID includes them and fully supports pagination.
WalkingSpeed = str  # open enum: WalkingSpeed
"""Cycle times of a line/trip in minutes."""
@dataclasses.dataclass
class Cycle:
    min: int = None
    max: int = None
    nr: int = None

    @classmethod
    def from_dict(cls, obj: Any) -> Cycle:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        min = obj.get("min")
        max = obj.get("max")
        nr = obj.get("nr")
        return cls(
            min=min,
            max=max,
            nr=nr,
        )

"""A departure or arrival board entry (OpenAPI schema name: Alternative)."""
@dataclasses.dataclass
class Departure:
    trip_id: str = None
    stop: Optional[StopOrStation] = None
    location: Optional[Location] = None
    line: Optional[Line] = None
    direction: str = None
    provenance: str = None
    origin: Optional[Place] = None
    destination: Optional[Place] = None
    when: _dt.datetime = None
    planned_when: _dt.datetime = None
    prognosed_when: _dt.datetime = None
    delay: int = None
    platform: str = None
    planned_platform: str = None
    prognosed_platform: str = None
    prognosis_type: Optional[PrognosisType] = None
    remarks: list[Optional[Remark]] = None
    cancelled: bool = None
    load_factor: str = None
    previous_stopovers: list[Optional[Stopover]] = None
    next_stopovers: list[Optional[Stopover]] = None
    frames: list[Optional[Frame]] = None
    polyline: Optional[Polyline] = None
    current_trip_position: Optional[Location] = None

    @classmethod
    def from_dict(cls, obj: Any) -> Departure:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        trip_id = obj.get("tripId")
        stop = obj.get("stop")
        location = (Location.from_dict(obj.get("location")) if isinstance(obj.get("location"), dict) else obj.get("location"))
        line = (Line.from_dict(obj.get("line")) if isinstance(obj.get("line"), dict) else obj.get("line"))
        direction = obj.get("direction")
        provenance = obj.get("provenance")
        origin = obj.get("origin")
        destination = obj.get("destination")
        when = (_parse_dt(obj.get("when")) if obj.get("when") is not None else None)
        planned_when = (_parse_dt(obj.get("plannedWhen")) if obj.get("plannedWhen") is not None else None)
        prognosed_when = (_parse_dt(obj.get("prognosedWhen")) if obj.get("prognosedWhen") is not None else None)
        delay = obj.get("delay")
        platform = obj.get("platform")
        planned_platform = obj.get("plannedPlatform")
        prognosed_platform = obj.get("prognosedPlatform")
        prognosis_type = obj.get("prognosisType")
        remarks = [Remark.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("remarks") or [])]
        cancelled = obj.get("cancelled")
        load_factor = obj.get("loadFactor")
        previous_stopovers = [Stopover.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("previousStopovers") or [])]
        next_stopovers = [Stopover.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("nextStopovers") or [])]
        frames = [Frame.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("frames") or [])]
        polyline = (Polyline.from_dict(obj.get("polyline")) if isinstance(obj.get("polyline"), dict) else obj.get("polyline"))
        current_trip_position = (Location.from_dict(obj.get("currentTripPosition")) if isinstance(obj.get("currentTripPosition"), dict) else obj.get("currentTripPosition"))
        return cls(
            trip_id=trip_id,
            stop=stop,
            location=location,
            line=line,
            direction=direction,
            provenance=provenance,
            origin=origin,
            destination=destination,
            when=when,
            planned_when=planned_when,
            prognosed_when=prognosed_when,
            delay=delay,
            platform=platform,
            planned_platform=planned_platform,
            prognosed_platform=prognosed_platform,
            prognosis_type=prognosis_type,
            remarks=remarks,
            cancelled=cancelled,
            load_factor=load_factor,
            previous_stopovers=previous_stopovers,
            next_stopovers=next_stopovers,
            frames=frames,
            polyline=polyline,
            current_trip_position=current_trip_position,
        )

"""Radar frame: position of a vehicle between two places at offset t."""
@dataclasses.dataclass
class Frame:
    origin: Optional[Place] = None
    destination: Optional[Place] = None
    t: float = None

    @classmethod
    def from_dict(cls, obj: Any) -> Frame:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        origin = obj.get("origin")
        destination = obj.get("destination")
        t = obj.get("t")
        return cls(
            origin=origin,
            destination=destination,
            t=t,
        )

"""GeoJSON Point geometry."""
@dataclasses.dataclass
class GeometryPoint:
    coordinates: list[float] = None

    @classmethod
    def from_dict(cls, obj: Any) -> GeometryPoint:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        coordinates = obj.get("coordinates")
        return cls(
            coordinates=coordinates,
        )

"""A computed set of directions to get from A to B at a specific time."""
@dataclasses.dataclass
class Journey:
    id: str = None
    refresh_token: str = None
    legs: list[Optional[Leg]] = None
    remarks: list[Optional[Remark]] = None
    price: Optional[Price] = None
    cycle: Optional[Cycle] = None
    service_days: Optional[ServiceDays] = None
    scheduled_days: Optional[ServiceDays] = None

    @classmethod
    def from_dict(cls, obj: Any) -> Journey:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        id = obj.get("id")
        refresh_token = obj.get("refreshToken")
        legs = [Leg.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("legs") or [])]
        remarks = [Remark.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("remarks") or [])]
        price = (Price.from_dict(obj.get("price")) if isinstance(obj.get("price"), dict) else obj.get("price"))
        cycle = (Cycle.from_dict(obj.get("cycle")) if isinstance(obj.get("cycle"), dict) else obj.get("cycle"))
        service_days = obj.get("serviceDays")
        scheduled_days = obj.get("scheduledDays")
        return cls(
            id=id,
            refresh_token=refresh_token,
            legs=legs,
            remarks=remarks,
            price=price,
            cycle=cycle,
            service_days=service_days,
            scheduled_days=scheduled_days,
        )

"""One leg of a journey. Walking/transfer legs have walking=true and no line."""
@dataclasses.dataclass
class Leg:
    trip_id: str = None
    origin: Optional[Place] = None
    destination: Optional[Place] = None
    line: Optional[Line] = None
    direction: str = None
    operator: Optional[Operator] = None
    departure: _dt.datetime = None
    planned_departure: _dt.datetime = None
    prognosed_departure: _dt.datetime = None
    departure_delay: int = None
    departure_platform: str = None
    planned_departure_platform: str = None
    prognosed_departure_platform: str = None
    departure_prognosis_type: Optional[PrognosisType] = None
    arrival: _dt.datetime = None
    planned_arrival: _dt.datetime = None
    prognosed_arrival: _dt.datetime = None
    arrival_delay: int = None
    arrival_platform: str = None
    planned_arrival_platform: str = None
    prognosed_arrival_platform: str = None
    arrival_prognosis_type: Optional[PrognosisType] = None
    stopovers: list[Optional[Stopover]] = None
    remarks: list[Optional[Remark]] = None
    walking: bool = None
    transfer: bool = None
    distance: float = None
    public: bool = None
    reachable: bool = None
    cancelled: bool = None
    load_factor: str = None
    cycle: Optional[Cycle] = None
    alternatives: list[Optional[Departure]] = None
    polyline: Optional[Polyline] = None
    price: Optional[Price] = None
    schedule: int = None
    current_location: Optional[Location] = None
    checkin: bool = None
    service_days: Optional[ServiceDays] = None
    scheduled_days: Optional[ServiceDays] = None

    @classmethod
    def from_dict(cls, obj: Any) -> Leg:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        trip_id = obj.get("tripId")
        origin = obj.get("origin")
        destination = obj.get("destination")
        line = (Line.from_dict(obj.get("line")) if isinstance(obj.get("line"), dict) else obj.get("line"))
        direction = obj.get("direction")
        operator = (Operator.from_dict(obj.get("operator")) if isinstance(obj.get("operator"), dict) else obj.get("operator"))
        departure = (_parse_dt(obj.get("departure")) if obj.get("departure") is not None else None)
        planned_departure = (_parse_dt(obj.get("plannedDeparture")) if obj.get("plannedDeparture") is not None else None)
        prognosed_departure = (_parse_dt(obj.get("prognosedDeparture")) if obj.get("prognosedDeparture") is not None else None)
        departure_delay = obj.get("departureDelay")
        departure_platform = obj.get("departurePlatform")
        planned_departure_platform = obj.get("plannedDeparturePlatform")
        prognosed_departure_platform = obj.get("prognosedDeparturePlatform")
        departure_prognosis_type = obj.get("departurePrognosisType")
        arrival = (_parse_dt(obj.get("arrival")) if obj.get("arrival") is not None else None)
        planned_arrival = (_parse_dt(obj.get("plannedArrival")) if obj.get("plannedArrival") is not None else None)
        prognosed_arrival = (_parse_dt(obj.get("prognosedArrival")) if obj.get("prognosedArrival") is not None else None)
        arrival_delay = obj.get("arrivalDelay")
        arrival_platform = obj.get("arrivalPlatform")
        planned_arrival_platform = obj.get("plannedArrivalPlatform")
        prognosed_arrival_platform = obj.get("prognosedArrivalPlatform")
        arrival_prognosis_type = obj.get("arrivalPrognosisType")
        stopovers = [Stopover.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("stopovers") or [])]
        remarks = [Remark.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("remarks") or [])]
        walking = obj.get("walking")
        transfer = obj.get("transfer")
        distance = obj.get("distance")
        public = obj.get("public")
        reachable = obj.get("reachable")
        cancelled = obj.get("cancelled")
        load_factor = obj.get("loadFactor")
        cycle = (Cycle.from_dict(obj.get("cycle")) if isinstance(obj.get("cycle"), dict) else obj.get("cycle"))
        alternatives = [Departure.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("alternatives") or [])]
        polyline = (Polyline.from_dict(obj.get("polyline")) if isinstance(obj.get("polyline"), dict) else obj.get("polyline"))
        price = (Price.from_dict(obj.get("price")) if isinstance(obj.get("price"), dict) else obj.get("price"))
        schedule = obj.get("schedule")
        current_location = (Location.from_dict(obj.get("currentLocation")) if isinstance(obj.get("currentLocation"), dict) else obj.get("currentLocation"))
        checkin = obj.get("checkin")
        service_days = obj.get("serviceDays")
        scheduled_days = obj.get("scheduledDays")
        return cls(
            trip_id=trip_id,
            origin=origin,
            destination=destination,
            line=line,
            direction=direction,
            operator=operator,
            departure=departure,
            planned_departure=planned_departure,
            prognosed_departure=prognosed_departure,
            departure_delay=departure_delay,
            departure_platform=departure_platform,
            planned_departure_platform=planned_departure_platform,
            prognosed_departure_platform=prognosed_departure_platform,
            departure_prognosis_type=departure_prognosis_type,
            arrival=arrival,
            planned_arrival=planned_arrival,
            prognosed_arrival=prognosed_arrival,
            arrival_delay=arrival_delay,
            arrival_platform=arrival_platform,
            planned_arrival_platform=planned_arrival_platform,
            prognosed_arrival_platform=prognosed_arrival_platform,
            arrival_prognosis_type=arrival_prognosis_type,
            stopovers=stopovers,
            remarks=remarks,
            walking=walking,
            transfer=transfer,
            distance=distance,
            public=public,
            reachable=reachable,
            cancelled=cancelled,
            load_factor=load_factor,
            cycle=cycle,
            alternatives=alternatives,
            polyline=polyline,
            price=price,
            schedule=schedule,
            current_location=current_location,
            checkin=checkin,
            service_days=service_days,
            scheduled_days=scheduled_days,
        )

"""A public transport line."""
@dataclasses.dataclass
class Line:
    id: str = None
    name: str = None
    additional_name: str = None
    admin_code: str = None
    fahrt_nr: str = None
    product: str = None
    product_name: str = None
    mode: Optional[Mode] = None
    operator: Optional[Operator] = None
    express: bool = None
    metro: bool = None
    night: bool = None
    nr: int = None
    symbol: str = None
    public: bool = None
    directions: list[str] = None
    routes: list[str] = None

    @classmethod
    def from_dict(cls, obj: Any) -> Line:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        id = obj.get("id")
        name = obj.get("name")
        additional_name = obj.get("additionalName")
        admin_code = obj.get("adminCode")
        fahrt_nr = obj.get("fahrtNr")
        product = obj.get("product")
        product_name = obj.get("productName")
        mode = obj.get("mode")
        operator = (Operator.from_dict(obj.get("operator")) if isinstance(obj.get("operator"), dict) else obj.get("operator"))
        express = obj.get("express")
        metro = obj.get("metro")
        night = obj.get("night")
        nr = obj.get("nr")
        symbol = obj.get("symbol")
        public = obj.get("public")
        directions = obj.get("directions")
        routes = obj.get("routes")
        return cls(
            id=id,
            name=name,
            additional_name=additional_name,
            admin_code=admin_code,
            fahrt_nr=fahrt_nr,
            product=product,
            product_name=product_name,
            mode=mode,
            operator=operator,
            express=express,
            metro=metro,
            night=night,
            nr=nr,
            symbol=symbol,
            public=public,
            directions=directions,
            routes=routes,
        )

"""A point: POI, address or bare coordinate."""
@dataclasses.dataclass
class Location:
    id: str = None
    name: str = None
    poi: bool = None
    address: str = None
    latitude: float = None
    longitude: float = None
    altitude: float = None
    distance: float = None

    @classmethod
    def from_dict(cls, obj: Any) -> Location:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        id = obj.get("id")
        name = obj.get("name")
        poi = obj.get("poi")
        address = obj.get("address")
        latitude = obj.get("latitude")
        longitude = obj.get("longitude")
        altitude = obj.get("altitude")
        distance = obj.get("distance")
        return cls(
            id=id,
            name=name,
            poi=poi,
            address=address,
            latitude=latitude,
            longitude=longitude,
            altitude=altitude,
            distance=distance,
        )

"""A vehicle currently moving in the radar area."""
@dataclasses.dataclass
class Movement:
    direction: str = None
    trip_id: str = None
    line: Optional[Line] = None
    location: Optional[Location] = None
    next_stopovers: list[Optional[Stopover]] = None
    frames: list[Optional[Frame]] = None
    polyline: Optional[Polyline] = None

    @classmethod
    def from_dict(cls, obj: Any) -> Movement:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        direction = obj.get("direction")
        trip_id = obj.get("tripId")
        line = (Line.from_dict(obj.get("line")) if isinstance(obj.get("line"), dict) else obj.get("line"))
        location = (Location.from_dict(obj.get("location")) if isinstance(obj.get("location"), dict) else obj.get("location"))
        next_stopovers = [Stopover.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("nextStopovers") or [])]
        frames = [Frame.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("frames") or [])]
        polyline = (Polyline.from_dict(obj.get("polyline")) if isinstance(obj.get("polyline"), dict) else obj.get("polyline"))
        return cls(
            direction=direction,
            trip_id=trip_id,
            line=line,
            location=location,
            next_stopovers=next_stopovers,
            frames=frames,
            polyline=polyline,
        )

"""Transit operator. Note: the upstream OpenAPI spec declares Trip.operator as number, but the wire format is an object; parsers must tolerate both."""
@dataclasses.dataclass
class Operator:
    id: str = None
    name: str = None

    @classmethod
    def from_dict(cls, obj: Any) -> Operator:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        id = obj.get("id")
        name = obj.get("name")
        return cls(
            id=id,
            name=name,
        )

"""GeoJSON FeatureCollection describing a trip/leg shape."""
@dataclasses.dataclass
class Polyline:
    features: list[Optional[PolylineFeature]] = None

    @classmethod
    def from_dict(cls, obj: Any) -> Polyline:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        features = [PolylineFeature.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("features") or [])]
        return cls(
            features=features,
        )

"""GeoJSON Feature; properties describe the stop located at this position."""
@dataclasses.dataclass
class PolylineFeature:
    properties: Optional[LocationResult] = None
    geometry: Optional[GeometryPoint] = None

    @classmethod
    def from_dict(cls, obj: Any) -> PolylineFeature:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        properties = obj.get("properties")
        geometry = (GeometryPoint.from_dict(obj.get("geometry")) if isinstance(obj.get("geometry"), dict) else obj.get("geometry"))
        return cls(
            properties=properties,
            geometry=geometry,
        )

"""Price information for a journey."""
@dataclasses.dataclass
class Price:
    amount: float = None
    currency: str = None
    hint: str = None

    @classmethod
    def from_dict(cls, obj: Any) -> Price:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        amount = obj.get("amount")
        currency = obj.get("currency")
        hint = obj.get("hint")
        return cls(
            amount=amount,
            currency=currency,
            hint=hint,
        )

"""Reachability result: travel duration and reachable stations."""
@dataclasses.dataclass
class ReachableDuration:
    duration: int = None
    stations: list[Optional[LocationResult]] = None

    @classmethod
    def from_dict(cls, obj: Any) -> ReachableDuration:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        duration = obj.get("duration")
        stations = obj.get("stations")
        return cls(
            duration=duration,
            stations=stations,
        )

"""Hint, status or warning attached to journeys/legs/departures/trips/stops. Merged model of FPTF hint/status/warning."""
@dataclasses.dataclass
class Remark:
    kind: Optional[RemarkKind] = None
    code: str = None
    summary: str = None
    text: str = None
    trip_id: str = None
    id: str = None
    priority: int = None
    category: str = None
    products: Optional[Products] = None
    company: str = None
    valid_from: _dt.datetime = None
    valid_until: _dt.datetime = None
    modified: _dt.datetime = None
    affected_lines: list[Optional[Line]] = None
    from_stops: list[Optional[LocationResult]] = None
    to_stops: list[Optional[LocationResult]] = None

    @classmethod
    def from_dict(cls, obj: Any) -> Remark:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        kind = obj.get("type")
        code = obj.get("code")
        summary = obj.get("summary")
        text = obj.get("text")
        trip_id = obj.get("tripId")
        id = obj.get("id")
        priority = obj.get("priority")
        category = obj.get("category")
        products = obj.get("products")
        company = obj.get("company")
        valid_from = (_parse_dt(obj.get("validFrom")) if obj.get("validFrom") is not None else None)
        valid_until = (_parse_dt(obj.get("validUntil")) if obj.get("validUntil") is not None else None)
        modified = (_parse_dt(obj.get("modified")) if obj.get("modified") is not None else None)
        affected_lines = [Line.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("affectedLines") or [])]
        from_stops = obj.get("fromStops")
        to_stops = obj.get("toStops")
        return cls(
            kind=kind,
            code=code,
            summary=summary,
            text=text,
            trip_id=trip_id,
            id=id,
            priority=priority,
            category=category,
            products=products,
            company=company,
            valid_from=valid_from,
            valid_until=valid_until,
            modified=modified,
            affected_lines=affected_lines,
            from_stops=from_stops,
            to_stops=to_stops,
        )

"""A larger station area possibly containing multiple stops."""
@dataclasses.dataclass
class Station:
    id: str = None
    name: str = None
    station: Optional[Station] = None
    location: Optional[Location] = None
    products: Optional[Products] = None
    lines: list[Optional[Line]] = None
    is_meta: bool = None
    regions: list[str] = None
    facilities: dict[str, str] = None
    opening_hours: Optional[OpeningHours] = None
    stops: list[Optional[LocationResult]] = None
    entrances: list[Optional[Location]] = None
    transit_authority: str = None
    distance: float = None

    @classmethod
    def from_dict(cls, obj: Any) -> Station:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        id = obj.get("id")
        name = obj.get("name")
        station = (Station.from_dict(obj.get("station")) if isinstance(obj.get("station"), dict) else obj.get("station"))
        location = (Location.from_dict(obj.get("location")) if isinstance(obj.get("location"), dict) else obj.get("location"))
        products = obj.get("products")
        lines = [Line.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("lines") or [])]
        is_meta = obj.get("isMeta")
        regions = obj.get("regions")
        facilities = obj.get("facilities")
        opening_hours = obj.get("reisezentrumOpeningHours")
        stops = obj.get("stops")
        entrances = [Location.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("entrances") or [])]
        transit_authority = obj.get("transitAuthority")
        distance = obj.get("distance")
        return cls(
            id=id,
            name=name,
            station=station,
            location=location,
            products=products,
            lines=lines,
            is_meta=is_meta,
            regions=regions,
            facilities=facilities,
            opening_hours=opening_hours,
            stops=stops,
            entrances=entrances,
            transit_authority=transit_authority,
            distance=distance,
        )

"""A single physical stop (platform, bus stop sign, ...)."""
@dataclasses.dataclass
class Stop:
    id: str = None
    name: str = None
    station: Optional[Station] = None
    location: Optional[Location] = None
    products: Optional[Products] = None
    ids: Optional[Ids] = None
    lines: list[Optional[Line]] = None
    entrances: list[Optional[Location]] = None
    is_meta: bool = None
    opening_hours: Optional[OpeningHours] = None
    load_factor: str = None
    transit_authority: str = None
    distance: float = None

    @classmethod
    def from_dict(cls, obj: Any) -> Stop:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        id = obj.get("id")
        name = obj.get("name")
        station = (Station.from_dict(obj.get("station")) if isinstance(obj.get("station"), dict) else obj.get("station"))
        location = (Location.from_dict(obj.get("location")) if isinstance(obj.get("location"), dict) else obj.get("location"))
        products = obj.get("products")
        ids = obj.get("ids")
        lines = [Line.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("lines") or [])]
        entrances = [Location.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("entrances") or [])]
        is_meta = obj.get("isMeta")
        opening_hours = obj.get("reisezentrumOpeningHours")
        load_factor = obj.get("loadFactor")
        transit_authority = obj.get("transitAuthority")
        distance = obj.get("distance")
        return cls(
            id=id,
            name=name,
            station=station,
            location=location,
            products=products,
            ids=ids,
            lines=lines,
            entrances=entrances,
            is_meta=is_meta,
            opening_hours=opening_hours,
            load_factor=load_factor,
            transit_authority=transit_authority,
            distance=distance,
        )

"""A vehicle stopping at a stop at specific times."""
@dataclasses.dataclass
class Stopover:
    stop: Optional[StopOrStation] = None
    arrival: _dt.datetime = None
    planned_arrival: _dt.datetime = None
    prognosed_arrival: _dt.datetime = None
    arrival_delay: int = None
    arrival_platform: str = None
    planned_arrival_platform: str = None
    prognosed_arrival_platform: str = None
    arrival_prognosis_type: Optional[PrognosisType] = None
    departure: _dt.datetime = None
    planned_departure: _dt.datetime = None
    prognosed_departure: _dt.datetime = None
    departure_delay: int = None
    departure_platform: str = None
    planned_departure_platform: str = None
    prognosed_departure_platform: str = None
    departure_prognosis_type: Optional[PrognosisType] = None
    remarks: list[Optional[Remark]] = None
    pass_by: bool = None
    cancelled: bool = None
    additional: bool = None

    @classmethod
    def from_dict(cls, obj: Any) -> Stopover:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        stop = obj.get("stop")
        arrival = (_parse_dt(obj.get("arrival")) if obj.get("arrival") is not None else None)
        planned_arrival = (_parse_dt(obj.get("plannedArrival")) if obj.get("plannedArrival") is not None else None)
        prognosed_arrival = (_parse_dt(obj.get("prognosedArrival")) if obj.get("prognosedArrival") is not None else None)
        arrival_delay = obj.get("arrivalDelay")
        arrival_platform = obj.get("arrivalPlatform")
        planned_arrival_platform = obj.get("plannedArrivalPlatform")
        prognosed_arrival_platform = obj.get("prognosedArrivalPlatform")
        arrival_prognosis_type = obj.get("arrivalPrognosisType")
        departure = (_parse_dt(obj.get("departure")) if obj.get("departure") is not None else None)
        planned_departure = (_parse_dt(obj.get("plannedDeparture")) if obj.get("plannedDeparture") is not None else None)
        prognosed_departure = (_parse_dt(obj.get("prognosedDeparture")) if obj.get("prognosedDeparture") is not None else None)
        departure_delay = obj.get("departureDelay")
        departure_platform = obj.get("departurePlatform")
        planned_departure_platform = obj.get("plannedDeparturePlatform")
        prognosed_departure_platform = obj.get("prognosedDeparturePlatform")
        departure_prognosis_type = obj.get("departurePrognosisType")
        remarks = [Remark.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("remarks") or [])]
        pass_by = obj.get("passBy")
        cancelled = obj.get("cancelled")
        additional = obj.get("additional")
        return cls(
            stop=stop,
            arrival=arrival,
            planned_arrival=planned_arrival,
            prognosed_arrival=prognosed_arrival,
            arrival_delay=arrival_delay,
            arrival_platform=arrival_platform,
            planned_arrival_platform=planned_arrival_platform,
            prognosed_arrival_platform=prognosed_arrival_platform,
            arrival_prognosis_type=arrival_prognosis_type,
            departure=departure,
            planned_departure=planned_departure,
            prognosed_departure=prognosed_departure,
            departure_delay=departure_delay,
            departure_platform=departure_platform,
            planned_departure_platform=planned_departure_platform,
            prognosed_departure_platform=prognosed_departure_platform,
            departure_prognosis_type=departure_prognosis_type,
            remarks=remarks,
            pass_by=pass_by,
            cancelled=cancelled,
            additional=additional,
        )

"""A specific vehicle stopping at a set of stops at specific times."""
@dataclasses.dataclass
class Trip:
    id: str = None
    origin: Optional[Place] = None
    destination: Optional[Place] = None
    line: Optional[Line] = None
    direction: str = None
    operator: Optional[Operator] = None
    departure: _dt.datetime = None
    planned_departure: _dt.datetime = None
    prognosed_departure: _dt.datetime = None
    departure_delay: int = None
    departure_platform: str = None
    planned_departure_platform: str = None
    prognosed_departure_platform: str = None
    departure_prognosis_type: Optional[PrognosisType] = None
    arrival: _dt.datetime = None
    planned_arrival: _dt.datetime = None
    prognosed_arrival: _dt.datetime = None
    arrival_delay: int = None
    arrival_platform: str = None
    planned_arrival_platform: str = None
    prognosed_arrival_platform: str = None
    arrival_prognosis_type: Optional[PrognosisType] = None
    stopovers: list[Optional[Stopover]] = None
    remarks: list[Optional[Remark]] = None
    walking: bool = None
    transfer: bool = None
    distance: float = None
    public: bool = None
    cancelled: bool = None
    load_factor: str = None
    cycle: Optional[Cycle] = None
    alternatives: list[Optional[Departure]] = None
    polyline: Optional[Polyline] = None
    price: Optional[Price] = None
    schedule: int = None
    current_location: Optional[Location] = None
    checkin: bool = None
    service_days: Optional[ServiceDays] = None
    scheduled_days: Optional[ServiceDays] = None

    @classmethod
    def from_dict(cls, obj: Any) -> Trip:
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        id = obj.get("id")
        origin = obj.get("origin")
        destination = obj.get("destination")
        line = (Line.from_dict(obj.get("line")) if isinstance(obj.get("line"), dict) else obj.get("line"))
        direction = obj.get("direction")
        operator = (Operator.from_dict(obj.get("operator")) if isinstance(obj.get("operator"), dict) else obj.get("operator"))
        departure = (_parse_dt(obj.get("departure")) if obj.get("departure") is not None else None)
        planned_departure = (_parse_dt(obj.get("plannedDeparture")) if obj.get("plannedDeparture") is not None else None)
        prognosed_departure = (_parse_dt(obj.get("prognosedDeparture")) if obj.get("prognosedDeparture") is not None else None)
        departure_delay = obj.get("departureDelay")
        departure_platform = obj.get("departurePlatform")
        planned_departure_platform = obj.get("plannedDeparturePlatform")
        prognosed_departure_platform = obj.get("prognosedDeparturePlatform")
        departure_prognosis_type = obj.get("departurePrognosisType")
        arrival = (_parse_dt(obj.get("arrival")) if obj.get("arrival") is not None else None)
        planned_arrival = (_parse_dt(obj.get("plannedArrival")) if obj.get("plannedArrival") is not None else None)
        prognosed_arrival = (_parse_dt(obj.get("prognosedArrival")) if obj.get("prognosedArrival") is not None else None)
        arrival_delay = obj.get("arrivalDelay")
        arrival_platform = obj.get("arrivalPlatform")
        planned_arrival_platform = obj.get("plannedArrivalPlatform")
        prognosed_arrival_platform = obj.get("prognosedArrivalPlatform")
        arrival_prognosis_type = obj.get("arrivalPrognosisType")
        stopovers = [Stopover.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("stopovers") or [])]
        remarks = [Remark.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("remarks") or [])]
        walking = obj.get("walking")
        transfer = obj.get("transfer")
        distance = obj.get("distance")
        public = obj.get("public")
        cancelled = obj.get("cancelled")
        load_factor = obj.get("loadFactor")
        cycle = (Cycle.from_dict(obj.get("cycle")) if isinstance(obj.get("cycle"), dict) else obj.get("cycle"))
        alternatives = [Departure.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("alternatives") or [])]
        polyline = (Polyline.from_dict(obj.get("polyline")) if isinstance(obj.get("polyline"), dict) else obj.get("polyline"))
        price = (Price.from_dict(obj.get("price")) if isinstance(obj.get("price"), dict) else obj.get("price"))
        schedule = obj.get("schedule")
        current_location = (Location.from_dict(obj.get("currentLocation")) if isinstance(obj.get("currentLocation"), dict) else obj.get("currentLocation"))
        checkin = obj.get("checkin")
        service_days = obj.get("serviceDays")
        scheduled_days = obj.get("scheduledDays")
        return cls(
            id=id,
            origin=origin,
            destination=destination,
            line=line,
            direction=direction,
            operator=operator,
            departure=departure,
            planned_departure=planned_departure,
            prognosed_departure=prognosed_departure,
            departure_delay=departure_delay,
            departure_platform=departure_platform,
            planned_departure_platform=planned_departure_platform,
            prognosed_departure_platform=prognosed_departure_platform,
            departure_prognosis_type=departure_prognosis_type,
            arrival=arrival,
            planned_arrival=planned_arrival,
            prognosed_arrival=prognosed_arrival,
            arrival_delay=arrival_delay,
            arrival_platform=arrival_platform,
            planned_arrival_platform=planned_arrival_platform,
            prognosed_arrival_platform=prognosed_arrival_platform,
            arrival_prognosis_type=arrival_prognosis_type,
            stopovers=stopovers,
            remarks=remarks,
            walking=walking,
            transfer=transfer,
            distance=distance,
            public=public,
            cancelled=cancelled,
            load_factor=load_factor,
            cycle=cycle,
            alternatives=alternatives,
            polyline=polyline,
            price=price,
            schedule=schedule,
            current_location=current_location,
            checkin=checkin,
            service_days=service_days,
            scheduled_days=scheduled_days,
        )

"""Result of location search / nearby: a stop, station, plain location or an unknown future type."""
LocationResult = object  # see from_dict dispatch below

"""Any place referenced by legs/trips/stopovers/frames."""
Place = object  # see from_dict dispatch below

"""A stop or a station."""
StopOrStation = object  # see from_dict dispatch below

"""Response of GET /stops/{id}/arrivals."""
@dataclasses.dataclass
class ArrivalsResponse:
    arrivals: list[Optional[Departure]] = None
    realtime_data_updated_at: int = None

    @classmethod
    def from_dict(cls, obj: Any) -> "ArrivalsResponse":
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        arrivals = [Departure.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("arrivals") or [])]
        realtime_data_updated_at = obj.get("realtimeDataUpdatedAt")
        return cls(
            arrivals=arrivals,
            realtime_data_updated_at=realtime_data_updated_at,
        )

"""Response of GET /stops/{id}/departures."""
@dataclasses.dataclass
class DeparturesResponse:
    departures: list[Optional[Departure]] = None
    realtime_data_updated_at: int = None

    @classmethod
    def from_dict(cls, obj: Any) -> "DeparturesResponse":
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        departures = [Departure.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("departures") or [])]
        realtime_data_updated_at = obj.get("realtimeDataUpdatedAt")
        return cls(
            departures=departures,
            realtime_data_updated_at=realtime_data_updated_at,
        )

"""Response of GET /journeys/{ref}."""
@dataclasses.dataclass
class JourneyResponse:
    journey: Optional[Journey] = None
    realtime_data_updated_at: int = None

    @classmethod
    def from_dict(cls, obj: Any) -> "JourneyResponse":
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        journey = (Journey.from_dict(obj.get("journey")) if isinstance(obj.get("journey"), dict) else obj.get("journey"))
        realtime_data_updated_at = obj.get("realtimeDataUpdatedAt")
        return cls(
            journey=journey,
            realtime_data_updated_at=realtime_data_updated_at,
        )

"""Response of GET /journeys."""
@dataclasses.dataclass
class JourneysResponse:
    journeys: list[Optional[Journey]] = None
    earlier_ref: str = None
    later_ref: str = None
    realtime_data_updated_at: int = None

    @classmethod
    def from_dict(cls, obj: Any) -> "JourneysResponse":
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        journeys = [Journey.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("journeys") or [])]
        earlier_ref = obj.get("earlierRef")
        later_ref = obj.get("laterRef")
        realtime_data_updated_at = obj.get("realtimeDataUpdatedAt")
        return cls(
            journeys=journeys,
            earlier_ref=earlier_ref,
            later_ref=later_ref,
            realtime_data_updated_at=realtime_data_updated_at,
        )

"""Response of GET /radar."""
@dataclasses.dataclass
class RadarResponse:
    movements: list[Optional[Movement]] = None
    realtime_data_updated_at: int = None

    @classmethod
    def from_dict(cls, obj: Any) -> "RadarResponse":
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        movements = [Movement.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("movements") or [])]
        realtime_data_updated_at = obj.get("realtimeDataUpdatedAt")
        return cls(
            movements=movements,
            realtime_data_updated_at=realtime_data_updated_at,
        )

"""Response of GET /stops/reachable-from."""
@dataclasses.dataclass
class ReachableFromResponse:
    reachable: list[Optional[ReachableDuration]] = None
    realtime_data_updated_at: int = None

    @classmethod
    def from_dict(cls, obj: Any) -> "ReachableFromResponse":
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        reachable = [ReachableDuration.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("reachable") or [])]
        realtime_data_updated_at = obj.get("realtimeDataUpdatedAt")
        return cls(
            reachable=reachable,
            realtime_data_updated_at=realtime_data_updated_at,
        )

"""Response of GET /trips/{id}."""
@dataclasses.dataclass
class TripResponse:
    trip: Optional[Trip] = None
    realtime_data_updated_at: int = None

    @classmethod
    def from_dict(cls, obj: Any) -> "TripResponse":
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        trip = (Trip.from_dict(obj.get("trip")) if isinstance(obj.get("trip"), dict) else obj.get("trip"))
        realtime_data_updated_at = obj.get("realtimeDataUpdatedAt")
        return cls(
            trip=trip,
            realtime_data_updated_at=realtime_data_updated_at,
        )

"""Response of GET /trips (trips by name)."""
@dataclasses.dataclass
class TripsResponse:
    trips: list[Optional[Trip]] = None
    realtime_data_updated_at: int = None

    @classmethod
    def from_dict(cls, obj: Any) -> "TripsResponse":
        obj = dict(obj)
        unknown = {k: v for k, v in obj.items()}
        _ = unknown  # unknown fields are intentionally ignored
        trips = [Trip.from_dict(i) if isinstance(i, dict) else i for i in (obj.get("trips") or [])]
        realtime_data_updated_at = obj.get("realtimeDataUpdatedAt")
        return cls(
            trips=trips,
            realtime_data_updated_at=realtime_data_updated_at,
        )

def parse_LocationResult(obj: Any) -> Any:
    """Dispatch on the wire `type` tag; returns raw dicts for unknown types."""
    if not isinstance(obj, dict):
        return obj
    tag = obj.get("type")
    if tag == "stop":
        try:
            return Stop.from_dict(obj)
        except Exception:
            pass
    if tag == "station":
        try:
            return Station.from_dict(obj)
        except Exception:
            pass
    if tag == "location":
        try:
            return Location.from_dict(obj)
        except Exception:
            pass
    return obj

def parse_Place(obj: Any) -> Any:
    """Dispatch on the wire `type` tag; returns raw dicts for unknown types."""
    if not isinstance(obj, dict):
        return obj
    tag = obj.get("type")
    if tag == "stop":
        try:
            return Stop.from_dict(obj)
        except Exception:
            pass
    if tag == "station":
        try:
            return Station.from_dict(obj)
        except Exception:
            pass
    if tag == "location":
        try:
            return Location.from_dict(obj)
        except Exception:
            pass
    return obj

def parse_StopOrStation(obj: Any) -> Any:
    """Dispatch on the wire `type` tag; returns raw dicts for unknown types."""
    if not isinstance(obj, dict):
        return obj
    tag = obj.get("type")
    if tag == "stop":
        try:
            return Stop.from_dict(obj)
        except Exception:
            pass
    if tag == "station":
        try:
            return Station.from_dict(obj)
        except Exception:
            pass
    return obj

