/* eslint-disable */
/**
 * Generated by transport-rest-gen. DO NOT EDIT.
 *
 * Source of truth: schema/*.json (see docs/API_ANALYSIS.md).
 */

// ---------------------------------------------------------------------------
// Shared aliases
// ---------------------------------------------------------------------------

/**
 * External identifiers (e.g. dhid, MDV, NASA).
 */
export type Ids = Record<string, string>;

/**
 * Weekday abbreviation -> hours string.
 */
export type OpeningHours = Record<string, string>;

/**
 * Profile-specific product flags keyed by product name.
 */
export type Products = Record<string, boolean>;

/**
 * ISO date -> served. db-vendo: serviceDays; hafas-client: scheduledDays.
 */
export type ServiceDays = Record<string, boolean>;

// ---------------------------------------------------------------------------
// Open enums (unknown values stay valid)
// ---------------------------------------------------------------------------

export type Accessibility =
  | 'partial'
  | 'complete'
  | (string & {});

export type AgeGroup =
  | 'B'
  | 'E'
  | 'K'
  | 'S'
  | 'Y'
  | (string & {});

/**
 * db-vendo backend profile selector of the DB instance.
 */
export type DbProfile =
  | 'dbnav'
  | 'db'
  | 'dbweb'
  | (string & {});

export type LoyaltyCard =
  | 'bahncard-1st-25'
  | 'bahncard-2nd-25'
  | 'bahncard-1st-50'
  | 'bahncard-2nd-50'
  | 'bahncard-1st-100'
  | 'bahncard-2nd-100'
  | 'vorteilscard'
  | 'halbtaxabo'
  | 'generalabonnement-1st'
  | 'generalabonnement-2nd'
  | 'nl-40'
  | 'at-klimaticket'
  | (string & {});

/**
 * Means of transport mode (FPTF). Open enum: unknown wire values map to the fallback variant.
 */
export type Mode =
  | 'aircraft'
  | 'bicycle'
  | 'bus'
  | 'car'
  | 'gondola'
  | 'taxi'
  | 'train'
  | 'walking'
  | 'watercraft'
  | (string & {});

/**
 * Reliability class of a prognosis.
 */
export type PrognosisType =
  | 'calculated'
  | 'prognosed'
  | (string & {});

/**
 * Discriminator of remark objects; FPTF hint/status/warning are merged into one model.
 */
export type RemarkKind =
  | 'hint'
  | 'status'
  | 'warning'
  | 'foreign-id'
  | 'local-fare-zone'
  | 'stop-dhid'
  | 'stop-website'
  | 'transit-authority'
  | (string & {});

/**
 * REALTIME is the default and excludes cancelled journeys; HYBRID includes them and fully supports pagination.
 */
export type RoutingMode =
  | 'FULL'
  | 'HYBRID'
  | 'INFOS'
  | 'OFF'
  | 'REALTIME'
  | 'SERVER_DEFAULT'
  | (string & {});

export type WalkingSpeed =
  | 'slow'
  | 'normal'
  | 'fast'
  | (string & {});

// ---------------------------------------------------------------------------
// Tagged unions (discriminated by `type`, unknown types captured verbatim)
// ---------------------------------------------------------------------------

/**
 * Result of location search / nearby: a stop, station, plain location or an unknown future type.
 */
export type LocationResult =
  | ({ type: 'stop'; } & Stop)
  | ({ type: 'station'; } & Station)
  | ({ type: 'location'; } & Location)
  | { type: (string & {}) };

/**
 * Any place referenced by legs/trips/stopovers/frames.
 */
export type Place =
  | ({ type: 'stop'; } & Stop)
  | ({ type: 'station'; } & Station)
  | ({ type: 'location'; } & Location)
  | { type: (string & {}) };

/**
 * A stop or a station.
 */
export type StopOrStation =
  | ({ type: 'stop'; } & Stop)
  | ({ type: 'station'; } & Station)
  | { type: (string & {}) };

// ---------------------------------------------------------------------------
// Models
// ---------------------------------------------------------------------------

/**
 * Cycle times of a line/trip in minutes.
 */
export interface Cycle {
  'min'?: number | null;
  'max'?: number | null;
  'nr'?: number | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * A departure or arrival board entry (OpenAPI schema name: Alternative).
 */
export interface Departure {
  'tripId'?: string | null;
  'stop'?: StopOrStation | null;
  /**
   * Current vehicle position (radar).
   */
  'location'?: Location | null;
  'line'?: Line | null;
  'direction'?: string | null;
  /**
   * Origin of the vehicle (arrivals boards).
   */
  'provenance'?: string | null;
  'origin'?: Place | null;
  'destination'?: Place | null;
  /**
   * Realtime time; null if cancelled.
   */
  'when'?: string | null;
  'plannedWhen'?: string | null;
  'prognosedWhen'?: string | null;
  /**
   * Seconds; null when unknown.
   */
  'delay'?: number | null;
  /**
   * Realtime platform; null if cancelled.
   */
  'platform'?: string | null;
  'plannedPlatform'?: string | null;
  'prognosedPlatform'?: string | null;
  'prognosisType'?: PrognosisType | null;
  'remarks'?: Remark[] | null;
  'cancelled'?: boolean | null;
  'loadFactor'?: string | null;
  'previousStopovers'?: Stopover[] | null;
  'nextStopovers'?: Stopover[] | null;
  /**
   * Radar frames.
   */
  'frames'?: Frame[] | null;
  'polyline'?: Polyline | null;
  'currentTripPosition'?: Location | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * Radar frame: position of a vehicle between two places at offset t.
 */
export interface Frame {
  'origin'?: Place | null;
  'destination'?: Place | null;
  't'?: number | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * GeoJSON Point geometry.
 */
export interface GeometryPoint {
  /**
   * [longitude, latitude].
   */
  'coordinates'?: number[] | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * A computed set of directions to get from A to B at a specific time.
 */
export interface Journey {
  'id'?: string | null;
  /**
   * Pass to refresh_journey for realtime updates.
   */
  'refreshToken'?: string | null;
  'legs': Leg[] | null;
  'remarks'?: Remark[] | null;
  'price'?: Price | null;
  'cycle'?: Cycle | null;
  'serviceDays'?: ServiceDays | null;
  'scheduledDays'?: ServiceDays | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * One leg of a journey. Walking/transfer legs have walking=true and no line.
 */
export interface Leg {
  'tripId'?: string | null;
  'origin': Place | null;
  'destination': Place | null;
  /**
   * Absent for walking/transfer legs.
   */
  'line'?: Line | null;
  'direction'?: string | null;
  'operator'?: Operator | null;
  'departure'?: string | null;
  'plannedDeparture'?: string | null;
  'prognosedDeparture'?: string | null;
  /**
   * Seconds.
   */
  'departureDelay'?: number | null;
  'departurePlatform'?: string | null;
  'plannedDeparturePlatform'?: string | null;
  'prognosedDeparturePlatform'?: string | null;
  'departurePrognosisType'?: PrognosisType | null;
  'arrival'?: string | null;
  'plannedArrival'?: string | null;
  'prognosedArrival'?: string | null;
  /**
   * Seconds.
   */
  'arrivalDelay'?: number | null;
  'arrivalPlatform'?: string | null;
  'plannedArrivalPlatform'?: string | null;
  'prognosedArrivalPlatform'?: string | null;
  'arrivalPrognosisType'?: PrognosisType | null;
  'stopovers'?: Stopover[] | null;
  'remarks'?: Remark[] | null;
  'walking'?: boolean | null;
  'transfer'?: boolean | null;
  /**
   * Meters (walking/cycling/driving legs).
   */
  'distance'?: number | null;
  'public'?: boolean | null;
  /**
   * Whether the transfer into this leg is guaranteed.
   */
  'reachable'?: boolean | null;
  'cancelled'?: boolean | null;
  'loadFactor'?: string | null;
  'cycle'?: Cycle | null;
  'alternatives'?: Departure[] | null;
  'polyline'?: Polyline | null;
  'price'?: Price | null;
  'schedule'?: number | null;
  'currentLocation'?: Location | null;
  'checkin'?: boolean | null;
  'serviceDays'?: ServiceDays | null;
  /**
   * hafas-client style; db-vendo uses serviceDays.
   */
  'scheduledDays'?: ServiceDays | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * A public transport line.
 */
export interface Line {
  'id'?: string | null;
  'name'?: string | null;
  'additionalName'?: string | null;
  'adminCode'?: string | null;
  'fahrtNr'?: string | null;
  /**
   * Profile-specific product key (open string).
   */
  'product'?: string | null;
  'productName'?: string | null;
  'mode'?: Mode | null;
  'operator'?: Operator | null;
  'express'?: boolean | null;
  'metro'?: boolean | null;
  'night'?: boolean | null;
  'nr'?: number | null;
  'symbol'?: string | null;
  'public'?: boolean | null;
  'directions'?: string[] | null;
  /**
   * Route ids.
   */
  'routes'?: string[] | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * A point: POI, address or bare coordinate.
 */
export interface Location {
  'id'?: string | null;
  'name'?: string | null;
  'poi'?: boolean | null;
  'address'?: string | null;
  'latitude'?: number | null;
  'longitude'?: number | null;
  'altitude'?: number | null;
  /**
   * Walking distance in meters (nearby results).
   */
  'distance'?: number | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * A vehicle currently moving in the radar area.
 */
export interface Movement {
  'direction'?: string | null;
  'tripId'?: string | null;
  'line'?: Line | null;
  'location'?: Location | null;
  'nextStopovers'?: Stopover[] | null;
  'frames'?: Frame[] | null;
  'polyline'?: Polyline | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * Transit operator. Note: the upstream OpenAPI spec declares Trip.operator as number, but the wire format is an object; parsers must tolerate both.
 */
export interface Operator {
  'id'?: string | null;
  'name'?: string | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * GeoJSON FeatureCollection describing a trip/leg shape.
 */
export interface Polyline {
  'features'?: PolylineFeature[] | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * GeoJSON Feature; properties describe the stop located at this position.
 */
export interface PolylineFeature {
  'properties'?: LocationResult | null;
  'geometry'?: GeometryPoint | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * Price information for a journey.
 */
export interface Price {
  'amount'?: number | null;
  'currency'?: string | null;
  'hint'?: string | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * Reachability result: travel duration and reachable stations.
 */
export interface ReachableDuration {
  /**
   * Seconds.
   */
  'duration'?: number | null;
  'stations'?: LocationResult[] | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * Hint, status or warning attached to journeys/legs/departures/trips/stops. Merged model of FPTF hint/status/warning.
 */
export interface Remark {
  'type': RemarkKind | null;
  'code'?: string | null;
  'summary'?: string | null;
  'text'?: string | null;
  'tripId'?: string | null;
  /**
   * Warning id.
   */
  'id'?: string | null;
  'priority'?: number | null;
  'category'?: string | null;
  'products'?: Products | null;
  'company'?: string | null;
  'validFrom'?: string | null;
  'validUntil'?: string | null;
  'modified'?: string | null;
  'affectedLines'?: Line[] | null;
  'fromStops'?: LocationResult[] | null;
  'toStops'?: LocationResult[] | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * A larger station area possibly containing multiple stops.
 */
export interface Station {
  'id': string | null;
  'name'?: string | null;
  'station'?: Station | null;
  'location'?: Location | null;
  'products'?: Products | null;
  'lines'?: Line[] | null;
  'isMeta'?: boolean | null;
  /**
   * Region ids.
   */
  'regions'?: string[] | null;
  'facilities'?: Record<string, string> | null;
  'reisezentrumOpeningHours'?: OpeningHours | null;
  /**
   * Sub-stops.
   */
  'stops'?: LocationResult[] | null;
  'entrances'?: Location[] | null;
  'transitAuthority'?: string | null;
  'distance'?: number | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * A single physical stop (platform, bus stop sign, ...).
 */
export interface Stop {
  'id': string | null;
  'name'?: string | null;
  /**
   * Parent station.
   */
  'station'?: Station | null;
  'location'?: Location | null;
  'products'?: Products | null;
  'ids'?: Ids | null;
  'lines'?: Line[] | null;
  'entrances'?: Location[] | null;
  'isMeta'?: boolean | null;
  'reisezentrumOpeningHours'?: OpeningHours | null;
  /**
   * Open value set: low/medium/high/...
   */
  'loadFactor'?: string | null;
  'transitAuthority'?: string | null;
  'distance'?: number | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * A vehicle stopping at a stop at specific times.
 */
export interface Stopover {
  'stop'?: StopOrStation | null;
  /**
   * Null/absent on the first stopover.
   */
  'arrival'?: string | null;
  'plannedArrival'?: string | null;
  'prognosedArrival'?: string | null;
  /**
   * Seconds.
   */
  'arrivalDelay'?: number | null;
  'arrivalPlatform'?: string | null;
  'plannedArrivalPlatform'?: string | null;
  'prognosedArrivalPlatform'?: string | null;
  'arrivalPrognosisType'?: PrognosisType | null;
  /**
   * Null/absent on the last stopover.
   */
  'departure'?: string | null;
  'plannedDeparture'?: string | null;
  'prognosedDeparture'?: string | null;
  /**
   * Seconds.
   */
  'departureDelay'?: number | null;
  'departurePlatform'?: string | null;
  'plannedDeparturePlatform'?: string | null;
  'prognosedDeparturePlatform'?: string | null;
  'departurePrognosisType'?: PrognosisType | null;
  'remarks'?: Remark[] | null;
  /**
   * Vehicle passes without stopping.
   */
  'passBy'?: boolean | null;
  'cancelled'?: boolean | null;
  /**
   * Extra, unscheduled stop.
   */
  'additional'?: boolean | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * A specific vehicle stopping at a set of stops at specific times.
 */
export interface Trip {
  'id': string | null;
  'origin'?: Place | null;
  'destination'?: Place | null;
  'line'?: Line | null;
  'direction'?: string | null;
  'operator'?: Operator | null;
  'departure'?: string | null;
  'plannedDeparture'?: string | null;
  'prognosedDeparture'?: string | null;
  'departureDelay'?: number | null;
  'departurePlatform'?: string | null;
  'plannedDeparturePlatform'?: string | null;
  'prognosedDeparturePlatform'?: string | null;
  'departurePrognosisType'?: PrognosisType | null;
  'arrival'?: string | null;
  'plannedArrival'?: string | null;
  'prognosedArrival'?: string | null;
  'arrivalDelay'?: number | null;
  'arrivalPlatform'?: string | null;
  'plannedArrivalPlatform'?: string | null;
  'prognosedArrivalPlatform'?: string | null;
  'arrivalPrognosisType'?: PrognosisType | null;
  'stopovers'?: Stopover[] | null;
  'remarks'?: Remark[] | null;
  'walking'?: boolean | null;
  'transfer'?: boolean | null;
  'distance'?: number | null;
  'public'?: boolean | null;
  'cancelled'?: boolean | null;
  'loadFactor'?: string | null;
  'cycle'?: Cycle | null;
  'alternatives'?: Departure[] | null;
  'polyline'?: Polyline | null;
  'price'?: Price | null;
  'schedule'?: number | null;
  'currentLocation'?: Location | null;
  'checkin'?: boolean | null;
  'serviceDays'?: ServiceDays | null;
  'scheduledDays'?: ServiceDays | null;
  [key: string]: unknown; // tolerate future fields
}

/**
 * Response of GET /stops/{id}/arrivals.
 */
export interface ArrivalsResponse {
  'arrivals': Departure[] | null;
  'realtimeDataUpdatedAt'?: number | null;
  [key: string]: unknown;
}

/**
 * Response of GET /stops/{id}/departures.
 */
export interface DeparturesResponse {
  'departures': Departure[] | null;
  'realtimeDataUpdatedAt'?: number | null;
  [key: string]: unknown;
}

/**
 * Response of GET /journeys/{ref}.
 */
export interface JourneyResponse {
  'journey': Journey | null;
  'realtimeDataUpdatedAt'?: number | null;
  [key: string]: unknown;
}

/**
 * Response of GET /journeys.
 */
export interface JourneysResponse {
  'journeys': Journey[] | null;
  'earlierRef'?: string | null;
  'laterRef'?: string | null;
  'realtimeDataUpdatedAt'?: number | null;
  [key: string]: unknown;
}

/**
 * Response of GET /radar.
 */
export interface RadarResponse {
  'movements': Movement[] | null;
  'realtimeDataUpdatedAt'?: number | null;
  [key: string]: unknown;
}

/**
 * Response of GET /stops/reachable-from.
 */
export interface ReachableFromResponse {
  'reachable': ReachableDuration[] | null;
  'realtimeDataUpdatedAt'?: number | null;
  [key: string]: unknown;
}

/**
 * Response of GET /trips/{id}.
 */
export interface TripResponse {
  'trip': Trip | null;
  'realtimeDataUpdatedAt'?: number | null;
  [key: string]: unknown;
}

/**
 * Response of GET /trips (trips by name).
 */
export interface TripsResponse {
  'trips': Trip[] | null;
  'realtimeDataUpdatedAt'?: number | null;
  [key: string]: unknown;
}

